CREATE TABLE [dbo].[iO_B2P_ProductMaster] (
    [PEpm_ID]                  VARCHAR (40) NOT NULL,
    [PEpm_Ownership]           VARCHAR (40) NULL,
    [PEpm_IDLink_Version]      VARCHAR (40) NULL,
    [PEpm_IDLink_Sync]         VARCHAR (40) NULL,
    [PEpm_SeqNumber]           BIGINT       IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [PEpm_IDLink_XRM]          VARCHAR (40) NULL,
    [PEpm_IDLink_XRP]          VARCHAR (40) NULL,
    [PEpm_DetailXML]           TEXT         NULL,
    [PEpm_ComboXML]            TEXT         NULL,
    [PEpm_Current]             BIT          NULL,
    [PEpm_Used]                INT          NULL,
    [PEpm_LoanAmtMin]          FLOAT (53)   NULL,
    [PEpm_LoanAmtMax]          FLOAT (53)   NULL,
    [PEpm_LVRMin]              FLOAT (53)   NULL,
    [PEpm_LVRMax]              FLOAT (53)   NULL,
    [PEpm_LoanTermMin]         INT          NULL,
    [PEpm_LoanTermMax]         INT          NULL,
    [PEpm_Impairment]          VARCHAR (40) NULL,
    [PEpm_InitialRate]         FLOAT (53)   NULL,
    [PEpm_InitialTerm]         INT          NULL,
    [PEpm_InterestOnlyTermMax] INT          NULL,
    [PEpm_BaseRate]            FLOAT (53)   NULL,
    [PEpm_DateStart]           DATETIME     NULL,
    [PEpm_DateEnd]             DATETIME     NULL,
    [PEpm_MiscXML]             TEXT         NULL,
    [PEpm_DateCreated]         DATETIME     NULL,
    [PEpm_DateExpired]         DATETIME     NULL,
    [PEpm_DateSystem]          DATETIME     NULL,
    [PEpm_ABNWithinWindow]     BIT          NULL,
    CONSTRAINT [PK_iO_B2P_ProductMaster] PRIMARY KEY CLUSTERED ([PEpm_ID] ASC) WITH (FILLFACTOR = 85)
);

