CREATE TABLE [dbo].[iO_Client_IndividualLiabilityCredit] (
    [CLLc_ID]               VARCHAR (40)  NOT NULL,
    [CLLc_Ownership]        VARCHAR (40)  NOT NULL,
    [CLLc_IDLink_Sync]      VARCHAR (40)  NULL,
    [CLLc_IDLink_Version]   VARCHAR (40)  NULL,
    [CLLc_IDLink_CMR]       VARCHAR (40)  NULL,
    [CLLc_IDLink_XLBc]      VARCHAR (40)  NULL,
    [CLLc_IDUser]           INT           NULL,
    [CLLc_Type]             INT           NULL,
    [CLLc_SeqNumber]        BIGINT        IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CLLc_CreditProvider]   VARCHAR (255) NULL,
    [CLLc_BalanceOwning]    FLOAT (53)    NULL,
    [CLLc_MonthlyRepayment] FLOAT (53)    NULL,
    [CLLc_Limit]            FLOAT (53)    NULL,
    [CLLc_DebtToContinue]   BIT           NULL,
    [CLLc_PayoutOption]     INT           NULL,
    [CLLc_IncludeGDS]       INT           NULL,
    [CLLc_IncludeTDS]       INT           NULL,
    [CLLc_InternalFlag]     INT           NULL,
    [CLLc_IsBureau]         INT           NULL,
    [CLLc_Note]             TEXT          NULL,
    [CLLc_AccountNumber]    VARCHAR (50)  NULL,
    [CLLc_PayoffAmount]     FLOAT (53)    NULL,
    [CLLc_Rate]             FLOAT (53)    NULL,
    [CLLc_BalanceOwing]     FLOAT (53)    NULL,
    [CLLc_TermRemainingM]   INT           NULL,
    CONSTRAINT [PK_iO_Client_IndividualLiabilityCredit] PRIMARY KEY CLUSTERED ([CLLc_ID] ASC) WITH (FILLFACTOR = 80)
);

