CREATE TABLE [dbo].[iO_Client_IndividualEmployment] (
    [CED_ID]                                  VARCHAR (40)  NOT NULL,
    [CED_Ownership]                           VARCHAR (40)  NOT NULL,
    [CED_IDLink_Version]                      VARCHAR (40)  NULL,
    [CED_IDLink_Sync]                         VARCHAR (40)  NULL,
    [CED_IDLink_CMR]                          VARCHAR (40)  NULL,
    [CED_IDLink_XCEt]                         VARCHAR (40)  NULL,
    [CED_IDLink_StreetType_C]                 VARCHAR (40)  NULL,
    [CED_IDLink_Country_C]                    VARCHAR (40)  NULL,
    [CED_IDLink_Occupation_C]                 VARCHAR (40)  NULL,
    [CED_IDLink_StreetType_P]                 VARCHAR (40)  NULL,
    [CED_IDLink_Country_P]                    VARCHAR (40)  NULL,
    [CED_SeqNumber]                           BIGINT        IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CED_Type]                                INT           NULL,
    [CED_IDUser]                              INT           NULL,
    [CED_EmployerName_C]                      VARCHAR (255) NULL,
    [CED_TimeInServiceY_C]                    INT           NULL,
    [CED_PropertyName_C]                      VARCHAR (255) NULL,
    [CED_UnitNumber_C]                        VARCHAR (50)  NULL,
    [CED_StreetNumber_C]                      VARCHAR (50)  NULL,
    [CED_StreetName_C]                        VARCHAR (255) NULL,
    [CED_City_C]                              VARCHAR (255) NULL,
    [CED_State_C]                             VARCHAR (255) NULL,
    [CED_PostCode_C]                          VARCHAR (10)  NULL,
    [CED_SuiteNumber_C]                       VARCHAR (50)  NULL,
    [CED_FloorNumber_C]                       VARCHAR (50)  NULL,
    [CED_ContactNumber_C]                     VARCHAR (50)  NULL,
    [CED_TimeInServiceM_C]                    INT           NULL,
    [CED_TimeInIndustryM_C]                   INT           NULL,
    [CED_TimeInIndustryY_C]                   INT           NULL,
    [CED_EmployerName_P]                      VARCHAR (255) NULL,
    [CED_TimeInServiceY_P]                    INT           NULL,
    [CED_PropertyName_P]                      VARCHAR (255) NULL,
    [CED_UnitNumber_P]                        VARCHAR (50)  NULL,
    [CED_StreetNumber_P]                      VARCHAR (50)  NULL,
    [CED_StreetName_P]                        VARCHAR (255) NULL,
    [CED_City_P]                              VARCHAR (255) NULL,
    [CED_State_P]                             VARCHAR (255) NULL,
    [CED_PostCode_P]                          VARCHAR (10)  NULL,
    [CED_TimeInServiceM_P]                    INT           NULL,
    [CED_ContactNumber_P]                     VARCHAR (50)  NULL,
    [CED_StartDate]                           SMALLDATETIME NULL,
    [CED_EndDate]                             SMALLDATETIME NULL,
    [CED_PrimaryEmployment]                   BIT           NULL,
    [CED_SelfEmployed]                        BIT           NULL,
    [CED_CurrentEmployment]                   BIT           NULL,
    [CED_OnProbation]                         BIT           NULL,
    [CED_PoorEmployment]                      BIT           NULL,
    [CED_PEGAAcceptable]                      BIT           NULL,
    [CED_EmploymentType]                      VARCHAR (512) NULL,
    [CED_Verification_ContactDetails]         VARCHAR (512) NULL,
    [CED_Verification_DateVerified]           DATETIME      NULL,
    [CED_Verification_EmployerPhone]          VARCHAR (50)  NULL,
    [CED_Verification_EmployerPhoneAreaCode]  VARCHAR (50)  NULL,
    [CED_Verification_EmployerPhoneISD]       VARCHAR (50)  NULL,
    [CED_VerificationName]                    VARCHAR (512) NULL,
    [CED_Verified]                            BIT           NULL,
    [CED_HighRisk]                            BIT           NULL,
    [CED_HighRiskOverride]                    BIT           NULL,
    [CED_Note]                                TEXT          NULL,
    [CED_Verification_EmployerFax]            VARCHAR (50)  NULL,
    [CED_Verification_EmployerFaxAreaCode]    VARCHAR (50)  NULL,
    [CED_Verification_EmployerFaxISD]         VARCHAR (50)  NULL,
    [CED_Verification_EmployerEmail]          VARCHAR (255) NULL,
    [CED_Verification_EmployerPhoneISDMob]    VARCHAR (50)  NULL,
    [CED_Verification_EmployerPhoneMob]       VARCHAR (255) NULL,
    [CED_JobTitle]                            VARCHAR (255) NULL,
    [CED_IDLink_XCI]                          VARCHAR (40)  NULL,
    [CED_Verification_EmployerPhoneExtension] VARCHAR (50)  NULL,
    [CED_TimeInServiceTot_C]                  INT           NULL,
    [CED_TimeInIndustryTot_C]                 INT           NULL,
    [CED_TypeOfBusiness]                      VARCHAR (MAX) NULL,
    [CED_EmployeePerformance]                 VARCHAR (40)  NULL,
    [CED_SalaryDeductionAvailable]            INT           NULL,
    [CED_HoursPerWeek]                        INT           NULL,
    [CED_EmployeeID]                          VARCHAR (50)  NULL,
    [CED_EmployeeAttention]                   VARCHAR (MAX) NULL,
    [CED_EmployeePayDay]                      VARCHAR (50)  NULL,
    [CED_EmployeeNextPayDate]                 DATETIME      NULL,
    [CED_IndustryType]                        VARCHAR (MAX) NULL,
    [CED_Area_C]                              VARCHAR (MAX) NULL,
    [CED_Area_P]                              VARCHAR (MAX) NULL,
    [CED_StartDate_P]                         SMALLDATETIME NULL,
    [CED_EndDate_P]                           SMALLDATETIME NULL,
    [CED_UnemployedReason]                    INT           NULL,
    [CED_SelfEmployedIncome]                  MONEY         NULL,
    [CED_SelfEmployedIncomePeriodY]           INT           NULL,
    [CED_SelfEmployedIncomePeriodM]           INT           NULL,
    [CED_ContractorTimeInContract]            INT           NULL,
    [CED_ContractorTermOfContractLeft]        INT           NULL,
    [CED_ContractorTradingHistY]              INT           NULL,
    [CED_ContractorTradingHistM]              INT           NULL,
    [CED_ContractorExperienceY]               INT           NULL,
    [CED_ContractorExperienceM]               INT           NULL,
    [CED_EmploymentBase]                      INT           NULL,
    [CED_EmploymentClass]                     INT           NULL,
    [CED_EmployerName]                        VARCHAR (MAX) NULL,
    [CED_EmployerTOB]                         VARCHAR (MAX) NULL,
    [CED_EmployerAddress]                     VARCHAR (MAX) NULL,
    [CED_EmployerContactName]                 VARCHAR (MAX) NULL,
    [CED_EmployerContactDetail]               VARCHAR (MAX) NULL,
    [CED_SelfEmployedType]                    INT           NULL,
    [CED_SelfEmployedCompanyName]             VARCHAR (MAX) NULL,
    [CED_SelfEmployedCompanyAddress]          VARCHAR (MAX) NULL,
    [CED_SelfEmployedTOB]                     VARCHAR (MAX) NULL,
    [CED_SelfEmployedShareHolding]            FLOAT (53)    NULL,
    [CED_SelfEmployedAccName]                 VARCHAR (MAX) NULL,
    [CED_SelfEmployedAccAddress]              VARCHAR (MAX) NULL,
    [CED_SelfEmployedAccContact]              VARCHAR (MAX) NULL,
    [CED_SelfEmployedAccNumber]               VARCHAR (MAX) NULL,
    [CED_ContractorCompanyName]               VARCHAR (MAX) NULL,
    [CED_ContractorLTDName]                   VARCHAR (MAX) NULL,
    [CED_ContractorLTDNumber]                 VARCHAR (MAX) NULL,
    [CED_ContractorFirmName]                  VARCHAR (MAX) NULL,
    [CED_ContractorFirmAddress]               VARCHAR (MAX) NULL,
    [CED_ContractorFirmREFName]               VARCHAR (MAX) NULL,
    [CED_ContractorFirmREFNumber]             VARCHAR (MAX) NULL,
    CONSTRAINT [PK_iO_CLient_EmploymentDetail] PRIMARY KEY CLUSTERED ([CED_ID] ASC) WITH (FILLFACTOR = 85)
);


GO
CREATE NONCLUSTERED INDEX [IX_iO_Client_IndividualEmployment]
    ON [dbo].[iO_Client_IndividualEmployment]([CED_IDLink_CMR] ASC) WITH (FILLFACTOR = 85);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Primary Key.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'iO_Client_IndividualEmployment', @level2type = N'COLUMN', @level2name = N'CED_ID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Redundant.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'iO_Client_IndividualEmployment', @level2type = N'COLUMN', @level2name = N'CED_Ownership';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Used to compare records in Replication process.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'iO_Client_IndividualEmployment', @level2type = N'COLUMN', @level2name = N'CED_IDLink_Version';

