CREATE TABLE [dbo].[iO_DNB_ResponseSeriousCreditInfringement] (
    [DNBsci_ID]                         VARCHAR (40)  NOT NULL,
    [DNBsci_Ownership]                  VARCHAR (40)  NULL,
    [DNBsci_IDLink_Version]             VARCHAR (40)  NULL,
    [DNBsci_IDLink_SCM]                 VARCHAR (40)  NULL,
    [DNBsci_IDLink_DNBmr]               VARCHAR (40)  NULL,
    [DNBsci_IDLink_Sync]                VARCHAR (40)  NULL,
    [DNBsci_SeqNumber]                  BIGINT        NULL,
    [DNBsci_SegID]                      VARCHAR (50)  NULL,
    [DNBsci_Sequence]                   VARCHAR (50)  NULL,
    [DNBsci_AccountTypeCode]            VARCHAR (50)  NULL,
    [DNBsci_AccountTypeDesc]            VARCHAR (255) NULL,
    [DNBsci_OriginalAmount]             VARCHAR (50)  NULL,
    [DNBsci_StatusCode]                 VARCHAR (50)  NULL,
    [DNBsci_StatusDesc]                 VARCHAR (255) NULL,
    [DNBsci_CurrentAmount]              VARCHAR (50)  NULL,
    [DNBsci_OriginalCustomerReference]  VARCHAR (50)  NULL,
    [DNBsci_CurrentCustomerReference]   VARCHAR (50)  NULL,
    [DNBsci_LastPaymentDate]            VARCHAR (50)  NULL,
    [DNBsci_DateOfDefault]              VARCHAR (50)  NULL,
    [DNBsci_Purpose]                    VARCHAR (50)  NULL,
    [DNBsci_CreditObligationCode]       VARCHAR (50)  NULL,
    [DNBsci_CreditObligationDesc]       VARCHAR (255) NULL,
    [DNBsci_OriginalCreditProvider]     VARCHAR (255) NULL,
    [DNBsci_CurrentCreditProvider]      VARCHAR (255) NULL,
    [DNBsci_OriginalReasonToReportDesc] VARCHAR (255) NULL,
    [DNBsci_OriginalReasonToReportCode] VARCHAR (50)  NULL,
    [DNBsci_CurrentReasonToReportDesc]  VARCHAR (255) NULL,
    [DNBsci_CurrentReasonToReportCode]  VARCHAR (50)  NULL,
    CONSTRAINT [PK_iO_DNB_ResponseSeriousCreditInfringement] PRIMARY KEY CLUSTERED ([DNBsci_ID] ASC) WITH (FILLFACTOR = 85)
);

