CREATE TABLE [dbo].[iO_EFX_Collections] (
    [EFXCOL_ID]                        VARCHAR (40) NULL,
    [EFXCOL_Ownership]                 VARCHAR (40) NULL,
    [EFXCOL_Version]                   VARCHAR (40) NULL,
    [EFXCOL_Sync]                      VARCHAR (40) NULL,
    [EFXCOL_Code]                      VARCHAR (40) NULL,
    [EFXCOL_Type]                      INT          NULL,
    [EFXCOL_IDUser]                    INT          NULL,
    [EFXCOL_IDLink_EFXRQ]              VARCHAR (40) NULL,
    [EFXCOL_IDLink_CMR]                VARCHAR (40) NULL,
    [EFXCOL_SeqNumber]                 BIGINT       IDENTITY (1, 1) NOT NULL,
    [EFXCOL_IDLink_EFXSBJ]             VARCHAR (40) NULL,
    [EFXCOL_Collection_code]           VARCHAR (2)  NULL,
    [EFXCOL_Collection_description]    VARCHAR (40) NULL,
    [EFXCOL_AssignedDate]              INT          NULL,
    [EFXCOL_AgencyId_CustomerNumber]   VARCHAR (10) NULL,
    [EFXCOL_AgencyId_Name]             VARCHAR (30) NULL,
    [EFXCOL_LedgerNumber]              VARCHAR (17) NULL,
    [EFXCOL_CC_AccountNumberAndOrName] VARCHAR (50) NULL,
    [EFXCOL_CCIndustry_code]           VARCHAR (2)  NULL,
    [EFXCOL_CCIndustry_description]    VARCHAR (30) NULL,
    [EFXCOL_Reason_code]               VARCHAR (1)  NULL,
    [EFXCOL_Reason_description]        VARCHAR (20) NULL,
    [EFXCOL_OriginalAmount]            INT          NULL,
    [EFXCOL_BalanceAmount]             INT          NULL,
    [EFXCOL_DateOfLastPayment]         INT          NULL,
    [EFXCOL_DatePaid]                  INT          NULL,
    [EFXCOL_VerificationDate]          INT          NULL,
    [EFXCOL_UpdateSource_code]         VARCHAR (1)  NULL,
    [EFXCOL_UpdateSource_description]  VARCHAR (20) NULL,
    [EFXCOL_NarrativeCode_1]           VARCHAR (2)  NULL,
    [EFXCOL_NarrativeCode_2]           VARCHAR (2)  NULL,
    [EFXCOL_Note]                      TEXT         NULL
);

