CREATE TABLE [dbo].[iO_EFX_Employment] (
    [EFXEmp_ID]                             VARCHAR (40) NULL,
    [EFXEmp_Ownership]                      VARCHAR (40) NULL,
    [EFXEmp_Version]                        VARCHAR (40) NULL,
    [EFXEmp_Sync]                           VARCHAR (40) NULL,
    [EFXEmp_Code]                           VARCHAR (40) NULL,
    [EFXEmp_IDLink_EFXRQ]                   VARCHAR (40) NULL,
    [EFXEmp_IDLink_CMR]                     VARCHAR (40) NULL,
    [EFXEmp_Type]                           INT          NULL,
    [EFXEmp_IDUser]                         INT          NULL,
    [EFXEmp_SeqNumber]                      BIGINT       IDENTITY (1, 1) NOT NULL,
    [EFXEmp_IDLink_EFXSBJ]                  VARCHAR (40) NULL,
    [EFXEmp_Employment_code]                VARCHAR (2)  NULL,
    [EFXEmp_Employment_description]         VARCHAR (40) NULL,
    [EFXEmp_Occupation]                     VARCHAR (25) NULL,
    [EFXEmp_Employer]                       VARCHAR (34) NULL,
    [EFXEmp_City]                           VARCHAR (20) NULL,
    [EFXEmp_Province_code]                  VARCHAR (2)  NULL,
    [EFXEmp_Province_description]           VARCHAR (25) NULL,
    [EFXEmp_DateEmployed]                   INT          NULL,
    [EFXEmp_DateLeft]                       INT          NULL,
    [EFXEmp_Verification_code]              VARCHAR (1)  NULL,
    [EFXEmp_Verification_description]       VARCHAR (20) NULL,
    [EFXEmp_Date]                           INT          NULL,
    [EFXEmp_SalaryAmount]                   INT          NULL,
    [EFXEmp_SalaryVerification_code]        VARCHAR (1)  NULL,
    [EFXEmp_SalaryVerification_description] VARCHAR (20) NULL,
    [EFXEmp_Note]                           TEXT         NULL
);

