CREATE TABLE [dbo].[iO_EFX_Garnishment] (
    [EFXGAR_ID]                       VARCHAR (40) NULL,
    [EFXGAR_Ownership]                VARCHAR (40) NULL,
    [EFXGAR_Version]                  VARCHAR (40) NULL,
    [EFXGAR_Sync]                     VARCHAR (40) NULL,
    [EFXGAR_Code]                     VARCHAR (40) NULL,
    [EFXGAR_Type]                     INT          NULL,
    [EFXGAR_IDUser]                   INT          NULL,
    [EFXGAR_IDLink_EFXRQ]             VARCHAR (40) NULL,
    [EFXGAR_IDLink_CMR]               VARCHAR (40) NULL,
    [EFXGAR_SeqNumber]                BIGINT       IDENTITY (1, 1) NOT NULL,
    [EFXGAR_IDLink_EFXSBJ]            VARCHAR (40) NULL,
    [EFXGAR_DateFiled]                INT          NULL,
    [EFXGAR_CourtID_CustomerNumber]   VARCHAR (10) NULL,
    [EFXGAR_CourtID_Name]             VARCHAR (30) NULL,
    [EFXGAR_CaseNumber]               VARCHAR (42) NULL,
    [EFXGAR_Amount]                   INT          NULL,
    [EFXGAR_DateSatisfied]            INT          NULL,
    [EFXGAR_VerificationDate]         INT          NULL,
    [EFXGAR_Plaintiff]                VARCHAR (42) NULL,
    [EFXGAR_Garnishee]                VARCHAR (40) NULL,
    [EFXGAR_Defendant]                VARCHAR (40) NULL,
    [EFXGAR_UpdateSource_code]        VARCHAR (1)  NULL,
    [EFXGAR_UpdateSource_description] VARCHAR (20) NULL,
    [EFXGAR_NarrativeCode_1]          VARCHAR (2)  NULL,
    [EFXGAR_NarrativeCode_2]          VARCHAR (2)  NULL,
    [EFXGAR_Note]                     TEXT         NULL
);

