CREATE TABLE [dbo].[iO_EFX_Address] (
    [EFXAdd_ID]                       VARCHAR (100) NOT NULL,
    [EFXAdd_Ownership]                VARCHAR (40)  NULL,
    [EFXAdd_Version]                  VARCHAR (40)  NULL,
    [EFXAdd_Sync]                     VARCHAR (40)  NULL,
    [EFXAdd_Code]                     VARCHAR (40)  NULL,
    [EFXAdd_Type]                     INT           NULL,
    [EFXAdd_IDUser]                   INT           NULL,
    [EFXAdd_IDLink_EFXRQ]             VARCHAR (40)  NULL,
    [EFXAdd_IDLink_CMR]               VARCHAR (40)  NULL,
    [EFXAdd_SeqNumber]                BIGINT        IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [EFXAdd_AddressType_code]         VARCHAR (2)   NULL,
    [EFXAdd_AddressType_description]  VARCHAR (40)  NULL,
    [EFXAdd_DateReported]             INT           NULL,
    [EFXAdd_CivicNumber]              VARCHAR (10)  NULL,
    [EFXAdd_StreetName]               VARCHAR (25)  NULL,
    [EFXAdd_City_description]         VARCHAR (20)  NULL,
    [EFXAdd_City_code]                VARCHAR (8)   NULL,
    [EFXAdd_Province_code]            VARCHAR (2)   NULL,
    [EFXAdd_Province_description]     VARCHAR (25)  NULL,
    [EFXAdd_PostalCode]               VARCHAR (6)   NULL,
    [EFXAdd_Occupancy_code]           VARCHAR (2)   NULL,
    [EFXAdd_Occupancy_description]    VARCHAR (1)   NULL,
    [EFXAdd_Date]                     VARCHAR (15)  NULL,
    [EFXAdd_UpdateSource_code]        INT           NULL,
    [EFXAdd_UpdateSource_description] INT           NULL,
    [EFXAdd_Note]                     TEXT          NULL,
    CONSTRAINT [io_efx_address_PrimaryKey] PRIMARY KEY CLUSTERED ([EFXAdd_ID] ASC)
);

