CREATE TABLE [dbo].[iO_FCX_LifeAndDisability_NonMortgageApplicant] (
    [FCXldn_ID]                                                           VARCHAR (40) NOT NULL,
    [FCXldn_IDLink_Ownership]                                             VARCHAR (40) NULL,
    [FCXldn_IDLink_Version]                                               VARCHAR (40) NULL,
    [FCXldn_IDLink_Sync]                                                  VARCHAR (40) NULL,
    [FCXldn_IDLink_Code]                                                  VARCHAR (40) NULL,
    [FCXldn_IDLink_SCM]                                                   VARCHAR (50) NULL,
    [FCXldn_IDLink_FCXld]                                                 VARCHAR (50) NULL,
    [FCXldn_SeqNumber]                                                    BIGINT       IDENTITY (1, 1) NOT NULL,
    [FCXldn_Address_UnitNumber]                                           VARCHAR (50) NULL,
    [FCXldn_Address_StreetNumber]                                         VARCHAR (50) NULL,
    [FCXldn_Address_StreetName]                                           VARCHAR (50) NULL,
    [FCXldn_Address_StreetType]                                           VARCHAR (50) NULL,
    [FCXldn_Address_StreetDirection]                                      VARCHAR (50) NULL,
    [FCXldn_Address_City]                                                 VARCHAR (50) NULL,
    [FCXldn_Address_Province]                                             VARCHAR (50) NULL,
    [FCXldn_Address_InternationalPostalcode]                              VARCHAR (50) NULL,
    [FCXldn_Address_PostalcodeFSA]                                        VARCHAR (50) NULL,
    [FCXldn_Address_PostalcodeLDU]                                        VARCHAR (50) NULL,
    [FCXldn_Address_Country]                                              VARCHAR (50) NULL,
    [FCXldn_DateOfBirth]                                                  VARCHAR (50) NULL,
    [FCXldn_Email]                                                        VARCHAR (50) NULL,
    [FCXldn_Employer]                                                     VARCHAR (50) NULL,
    [FCXldn_EmploymentYear]                                               VARCHAR (50) NULL,
    [FCXldn_EmploymentMonth]                                              VARCHAR (50) NULL,
    [FCXldn_Gender]                                                       VARCHAR (50) NULL,
    [FCXldn_FirstName]                                                    VARCHAR (50) NULL,
    [FCXldn_LastName]                                                     VARCHAR (50) NULL,
    [FCXldn_PreferredContact]                                             VARCHAR (50) NULL,
    [FCXldn_Smoker]                                                       VARCHAR (50) NULL,
    [FCXldn_InsuranceDetails_CoverageType]                                VARCHAR (50) NULL,
    [FCXldn_InsuranceDetails_InsuranceProportions]                        VARCHAR (50) NULL,
    [FCXldn_InsuranceDetails_Amortization]                                VARCHAR (50) NULL,
    [FCXldn_InsuranceDetails_InsuredAmount]                               VARCHAR (50) NULL,
    [FCXldn_InsuranceDetails_TotalLoanAmtExceeded]                        VARCHAR (50) NULL,
    [FCXldn_InsuranceDetails_HealthDeclaration_HealthCompleted]           VARCHAR (50) NULL,
    [FCXldn_InsuranceDetails_HealthDeclaration_HealthDeclarationRequired] VARCHAR (50) NULL,
    [FCXldn_InsuranceDetails_HealthDeclaration_longFormRequired]          VARCHAR (50) NULL,
    [FCXldn_InsuranceDetails_HealthDeclaration_HealthQuestion1]           VARCHAR (50) NULL,
    [FCXldn_InsuranceDetails_HealthDeclaration_HealthQuestion2]           VARCHAR (50) NULL,
    [FCXldn_InsuranceDetails_HealthDeclaration_HealthQuestion3]           VARCHAR (50) NULL,
    [FCXldn_InsuranceDetails_HealthDeclaration_HealthQuestion4]           VARCHAR (50) NULL
);

