CREATE TABLE [dbo].[iO_FNF_FileStatus] (
    [FNFfs_ID]                      VARCHAR (40)  NULL,
    [FNFfs_IDLink_Ownership]        VARCHAR (40)  NULL,
    [FNFfs_IDLink_Version]          VARCHAR (40)  NULL,
    [FNFfs_IDLink_Sync]             VARCHAR (40)  NULL,
    [FNFfs_IDLink_Code]             VARCHAR (40)  NULL,
    [FNFfs_IDLink_SCM]              VARCHAR (50)  NULL,
    [FNFfs_SeqNumber]               INT           NULL,
    [FNFfs_FileNumber]              VARCHAR (50)  NULL,
    [FNFfs_MortgageNumber]          VARCHAR (50)  NULL,
    [FNFfs_Party]                   VARCHAR (50)  NULL,
    [FNFfs_Province]                VARCHAR (50)  NULL,
    [FNFfs_Program]                 VARCHAR (50)  NULL,
    [FNFfs_Opened]                  VARCHAR (50)  NULL,
    [FNFfs_Priority]                VARCHAR (50)  NULL,
    [FNFfs_Stage]                   VARCHAR (50)  NULL,
    [FNFfs_InProcess]               VARCHAR (50)  NULL,
    [FNFfs_Closing]                 VARCHAR (50)  NULL,
    [FNFfs_Office]                  VARCHAR (50)  NULL,
    [FNFfs_SalesContact]            VARCHAR (50)  NULL,
    [FNFfs_Funder]                  VARCHAR (50)  NULL,
    [FNFfs_Underwriter]             VARCHAR (50)  NULL,
    [FNFfs_TitleInsurance]          VARCHAR (50)  NULL,
    [FNFfs_RegNumber]               VARCHAR (50)  NULL,
    [FNFfs_ActivationStatus]        VARCHAR (50)  NULL,
    [FNFfs_PropertyAddress]         VARCHAR (MAX) NULL,
    [FNFfs_PartyAddress]            VARCHAR (MAX) NULL,
    [FNFfs_LegalProperyDescription] VARCHAR (50)  NULL,
    [FNFfs_FundingStatus]           VARCHAR (50)  NULL,
    [FNFfs_FundsRequested]          VARCHAR (50)  NULL,
    [FNFfs_Processing]              VARCHAR (50)  NULL,
    [FNFfs_Signing]                 VARCHAR (50)  NULL,
    [FNFfs_Funding]                 VARCHAR (50)  NULL,
    [FNFfs_Registration]            VARCHAR (50)  NULL,
    [FNFfs_Reporting]               VARCHAR (50)  NULL
);

