CREATE TABLE [dbo].[iO_MOR_LoanDetails] (
    [MORld_ID]                       VARCHAR (40)  NULL,
    [MORld_Ownership]                VARCHAR (50)  NULL,
    [MORld_Version]                  VARCHAR (10)  NULL,
    [MORld_Sync]                     VARCHAR (10)  NULL,
    [MORld_Code]                     VARCHAR (10)  NULL,
    [MORld_Type]                     VARCHAR (10)  NULL,
    [MORld_IDLink_MORac]             VARCHAR (40)  NULL,
    [MORld_LOANAMOUNT]               DECIMAL (18)  NULL,
    [MORld_PAYMENTAMOUNT]            DECIMAL (18)  NULL,
    [MORld_REQUESTEDPAYMENT]         DECIMAL (18)  NULL,
    [MORld_PAYMENTFREQUENCY]         INT           NULL,
    [MORld_FIRSTPAYMENTDATE]         SMALLDATETIME NULL,
    [MORld_MONTHENDINDICATOR]        INT           NULL,
    [MORld_ACCELERATEDPAYMENTIND]    BIT           NULL,
    [MORld_INTERESTADJUSTMENTDATE]   SMALLDATETIME NULL,
    [MORld_MATURITYDATE]             SMALLDATETIME NULL,
    [MORld_REPAYMENTTYPE]            INT           NULL,
    [MORld_NETRATE]                  DECIMAL (18)  NULL,
    [MORld_BLENDEDAMORTIZATIONIND]   BIT           NULL,
    [MORld_AMORTIZATIONINMONTHS]     TINYINT       NULL,
    [MORld_AMORTIZATIONINYEARS]      TINYINT       NULL,
    [MORld_PRODUCTTERMINMONTHS]      TINYINT       NULL,
    [MORld_PRODUCTTERMINYEARS]       TINYINT       NULL,
    [MORld_PRODUCTCODE]              VARCHAR (6)   NULL,
    [MORld_PREPAYMENTOPTION]         INT           NULL,
    [MORld_EARLYPAYOUTOPTION]        INT           NULL,
    [MORld_CASHBACKPERCENTAGE]       INT           NULL,
    [MORld_RATECOMPOUNDINGFREQUENCY] INT           NULL,
    [MORld_RATECHANGEFREQUENCY]      INT           NULL,
    [MORld_ADJUSTMENT]               DECIMAL (18)  NULL,
    [MORld_ADJUSTMENTREASON]         INT           NULL,
    [MORld_ADJUSTMENTBUYDOWN]        DECIMAL (18)  NULL,
    [MORld_BUYDOWNAMOUNT]            DECIMAL (18)  NULL
);

