CREATE TABLE [dbo].[iO_MOR_AddionalFinancingLoanDetails] (
    [MORafld_ID]                       VARCHAR (40)  NULL,
    [MORafld_Ownership]                VARCHAR (50)  NULL,
    [MORafld_Version]                  VARCHAR (10)  NULL,
    [MORafld_Sync]                     VARCHAR (10)  NULL,
    [MORafld_Code]                     VARCHAR (10)  NULL,
    [MORafld_Type]                     VARCHAR (10)  NULL,
    [MORafld_IDLink_MORafc]            VARCHAR (40)  NULL,
    [MORafld_LOANAMOUNT]               DECIMAL (18)  NULL,
    [MORafld_PAYMENTAMOUNT]            DECIMAL (18)  NULL,
    [MORafld_REQUESTEDPAYMENT]         DECIMAL (18)  NULL,
    [MORafld_PAYMENTFREQUENCY]         INT           NULL,
    [MORafld_FIRSTPAYMENTDATE]         SMALLDATETIME NULL,
    [MORafld_MONTHENDINDICATOR]        INT           NULL,
    [MORafld_ACCELERATEDPAYMENTIND]    BIT           NULL,
    [MORafld_INTERESTADJUSTMENTDATE]   SMALLDATETIME NULL,
    [MORafld_MATURITYDATE]             SMALLDATETIME NULL,
    [MORafld_REPAYMENTTYPE]            INT           NULL,
    [MORafld_NETRATE]                  DECIMAL (18)  NULL,
    [MORafld_BLENDEDAMORTIZATIONIND]   BIT           NULL,
    [MORafld_AMORTIZATIONINMONTHS]     TINYINT       NULL,
    [MORafld_AMORTIZATIONINYEARS]      TINYINT       NULL,
    [MORafld_PRODUCTTERMINMONTHS]      TINYINT       NULL,
    [MORafld_PRODUCTTERMINYEARS]       TINYINT       NULL,
    [MORafld_PRODUCTCODE]              VARCHAR (6)   NULL,
    [MORafld_PREPAYMENTOPTION]         INT           NULL,
    [MORafld_EARLYPAYOUTOPTION]        INT           NULL,
    [MORafld_CASHBACKPERCENTAGE]       INT           NULL,
    [MORafld_RATECOMPOUNDINGFREQUENCY] INT           NULL,
    [MORafld_RATECHANGEFREQUENCY]      INT           NULL,
    [MORafld_ADJUSTMENT]               DECIMAL (18)  NULL,
    [MORafld_ADJUSTMENTREASON]         INT           NULL,
    [MORafld_ADJUSTMENTBUYDOWN]        DECIMAL (18)  NULL,
    [MORafld_BUYDOWNAMOUNT]            DECIMAL (18)  NULL
);

