CREATE TABLE [dbo].[iO_MOR_Employment] (
    [MORemp_ID]                       VARCHAR (40)  NULL,
    [MORemp_Ownership]                VARCHAR (50)  NULL,
    [MORemp_Version]                  VARCHAR (10)  NULL,
    [MORemp_Sync]                     VARCHAR (10)  NULL,
    [MORemp_Code]                     VARCHAR (10)  NULL,
    [MORemp_Type]                     VARCHAR (10)  NULL,
    [MORemp_IDLink_MORcv]             VARCHAR (40)  NULL,
    [MORemp_EMPLOYMENTTYPE]           INT           NULL,
    [MORemp_EMPLOYMENTSTATUS]         INT           NULL,
    [MORemp_DATELEFTORCEASEDTRADING]  SMALLDATETIME NULL,
    [MORemp_DATESTARTEDORESTABLISHED] SMALLDATETIME NULL,
    [MORemp_INDUSTRYTYPE]             INT           NULL,
    [MORemp_OCCUPATIONTYPE]           INT           NULL,
    [MORemp_JOBTITLE]                 VARCHAR (50)  NULL,
    [MORemp_COMPANYNAME]              VARCHAR (50)  NULL,
    [MORemp_TELEPHONENUMBER]          VARCHAR (30)  NULL,
    [MORemp_MAINSTATUS]               BIT           NULL,
    [MORemp_POSTALCODE]               VARCHAR (8)   NULL,
    [MORemp_APTORUNITNUMBER]          VARCHAR (10)  NULL,
    [MORemp_BUILDINGORHOUSENUMBER]    VARCHAR (10)  NULL,
    [MORemp_STREET]                   VARCHAR (40)  NULL,
    [MORemp_STREETDIRECTION]          INT           NULL,
    [MORemp_STREETTYPE]               INT           NULL,
    [MORemp_RRORPOBOXNUMBER]          VARCHAR (40)  NULL,
    [MORemp_TOWN]                     VARCHAR (40)  NULL,
    [MORemp_PROVINCESEQNO]            INT           NULL,
    [MORemp_COUNTRY]                  INT           NULL
);

