CREATE TABLE [dbo].[iO_Product_SecurityPTYPIP] (
    [RSPp_ID]               VARCHAR (40)  NOT NULL,
    [RSPp_Ownership]        VARCHAR (40)  NULL,
    [RSPp_IDLink_Sync]      VARCHAR (40)  NULL,
    [RSPp_IDLink_Version]   VARCHAR (40)  NULL,
    [RSPp_SeqNumber]        BIGINT        IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [RSPp_IDLink_RSP]       VARCHAR (40)  NOT NULL,
    [RSPp_PIPInsured]       VARCHAR (500) NULL,
    [RSPp_InsuranceAmount]  FLOAT (53)    NULL,
    [RSPp_InsuranceExpiry]  DATETIME      NULL,
    [RSPp_Agent1]           VARCHAR (MAX) NULL,
    [RSPp_Apprasial_1_Low]  FLOAT (53)    NULL,
    [RSPp_Apprasial_1_High] FLOAT (53)    NULL,
    [RSPp_Agent2]           VARCHAR (MAX) NULL,
    [RSPp_Apprasial_2_Low]  FLOAT (53)    NULL,
    [RSPp_Apprasial_2_High] FLOAT (53)    NULL,
    [RSPp_Valuer1]          VARCHAR (500) NULL,
    [RSPp_Valuation_1_FS]   FLOAT (53)    NULL,
    [RSPp_Valuation_1_MV]   FLOAT (53)    NULL,
    [RSPp_ValuationDate1]   DATETIME      NULL,
    [RSPp_Valuer2]          VARCHAR (500) NULL,
    [RSPp_Valuation_2_MV]   FLOAT (53)    NULL,
    [RSPp_Valuation_2_FS]   FLOAT (53)    NULL,
    [RSPp_ValuationDate2]   DATETIME      NULL,
    [RSPp_Valuer3]          VARCHAR (500) NULL,
    [RSPp_Valuation_3_FS]   FLOAT (53)    NULL,
    [RSPp_Valuation_3_MV]   FLOAT (53)    NULL,
    [RSPp_ValuationDate3]   DATETIME      NULL,
    [RSPp_AuctionDate]      DATETIME      NULL,
    [RSPp_AuctionSold]      VARCHAR (50)  NULL,
    [RSPp_SoldDate]         DATETIME      NULL,
    [RSPp_SoldAmount]       FLOAT (53)    NULL,
    [RSPp_ListedSaleDate]   DATETIME      NULL,
    [RSPp_SaleType]         VARCHAR (50)  NULL,
    [RSPp_ListedAmount]     FLOAT (53)    NULL,
    [RSPp_AuctionReserve]   FLOAT (53)    NULL,
    [RSPp_PrivateTreaty]    VARCHAR (50)  NULL,
    CONSTRAINT [PK_iO_Product_SecurityPTYPiP] PRIMARY KEY CLUSTERED ([RSPp_ID] ASC) WITH (FILLFACTOR = 85)
);

