CREATE TABLE [dbo].[iO_Product_LoanAssetPropertyMortgage] (
    [RLAPm_ID]                                  VARCHAR (40)  NOT NULL,
    [RLAPm_Ownership]                           VARCHAR (40)  NULL,
    [RLAPm_IDLink_RLAp]                         VARCHAR (40)  NULL,
    [RLAPm_IDLink_Holder]                       VARCHAR (40)  NULL,
    [RLAPm_IDLink_XMT]                          VARCHAR (40)  NULL,
    [RLAPm_IDLink_XRPM]                         VARCHAR (40)  NULL,
    [RLAPm_Amount]                              FLOAT (53)    NULL,
    [RLAPm_DeedOfPriority]                      BIT           NULL,
    [RLAPm_BMSAmount]                           FLOAT (53)    NULL,
    [RLAPm_SubsequentType]                      VARCHAR (50)  NULL,
    [RLAPm_Notes]                               TEXT          NULL,
    [RLAPm_IDLink_Sync]                         VARCHAR (40)  NULL,
    [RLAPm_IDLink_Version]                      VARCHAR (40)  NULL,
    [RLAPm_IDUser]                              INT           NULL,
    [RLAPm_Type]                                INT           NULL,
    [RLAPm_SeqNumber]                           BIGINT        NULL,
    [RLAPm_FCXActualPaymentTerm]                VARCHAR (50)  NULL,
    [RLAPm_FCXAdditionalPrincipal]              VARCHAR (50)  NULL,
    [RLAPm_FCXAdminFee]                         VARCHAR (50)  NULL,
    [RLAPm_FCXAffiliationProgram]               VARCHAR (50)  NULL,
    [RLAPm_FCXAmortTerm]                        VARCHAR (50)  NULL,
    [RLAPm_FCXBalanceRemaining]                 VARCHAR (50)  NULL,
    [RLAPm_FCXCashBackAmt]                      VARCHAR (50)  NULL,
    [RLAPm_FCXCashBackOverride]                 VARCHAR (50)  NULL,
    [RLAPm_FCXCashBackPercentage]               VARCHAR (50)  NULL,
    [RLAPm_FCXCurrentMtgNumber]                 VARCHAR (50)  NULL,
    [RLAPm_FCXEffectiveAmort]                   VARCHAR (50)  NULL,
    [RLAPm_FCXExistingMtgFlag]                  VARCHAR (50)  NULL,
    [RLAPm_FCXExistingMtgHolder]                VARCHAR (50)  NULL,
    [RLAPm_FCXFirstPamentDate]                  VARCHAR (50)  NULL,
    [RLAPm_FCXInsuredFlag]                      VARCHAR (50)  NULL,
    [RLAPm_FCXInterestAdjustAmout]              VARCHAR (50)  NULL,
    [RLAPm_FCXInterestAdjustDate]               VARCHAR (50)  NULL,
    [RLAPm_FCXInterestCompound]                 VARCHAR (50)  NULL,
    [RLAPm_FCXInterestOnlyFlag]                 VARCHAR (50)  NULL,
    [RLAPm_FCXRepaymentType]                    VARCHAR (50)  NULL,
    [RLAPm_FCXInterestType]                     VARCHAR (50)  NULL,
    [RLAPm_FCXLenderSubLanguage]                VARCHAR (50)  NULL,
    [RLAPm_FCXLenderSubLenderName]              VARCHAR (50)  NULL,
    [RLAPm_FCXLenderSubLenderCode]              VARCHAR (50)  NULL,
    [RLAPm_FCXLenderSubLenderLinkID]            VARCHAR (50)  NULL,
    [RLAPm_FCXLenderSubLenderRegistrationName]  VARCHAR (50)  NULL,
    [RLAPm_FCXLenderSubUseLegacyUserID]         VARCHAR (50)  NULL,
    [RLAPm_FCXLenderOriginatorNotes]            TEXT          NULL,
    [RLAPm_FCXLenderRoutingReceiver]            VARCHAR (50)  NULL,
    [RLAPm_FCXLenderRoutingSender]              VARCHAR (50)  NULL,
    [RLAPm_FCXLenderSubmitRequestTime]          VARCHAR (50)  NULL,
    [RLAPm_FCXLineOfBusiness]                   VARCHAR (50)  NULL,
    [RLAPm_FCXLoanType]                         VARCHAR (50)  NULL,
    [RLAPm_FCXLOCRepaymentType]                 VARCHAR (50)  NULL,
    [RLAPm_FCXLTV]                              VARCHAR (50)  NULL,
    [RLAPm_FCXMarketSubmission]                 VARCHAR (50)  NULL,
    [RLAPm_FCXMarketSubmissionNumber]           VARCHAR (50)  NULL,
    [RLAPm_FCXMaturityDate]                     VARCHAR (50)  NULL,
    [RLAPm_FCXMIFeeAmount]                      VARCHAR (50)  NULL,
    [RLAPm_FCXMIPremiumAmount]                  VARCHAR (50)  NULL,
    [RLAPm_FCXMIPremiumPST]                     VARCHAR (50)  NULL,
    [RLAPm_FCXMIReferenceNumber]                VARCHAR (50)  NULL,
    [RLAPm_FCXMortgageInsurerID]                VARCHAR (50)  NULL,
    [RLAPm_FCXMortgageType]                     VARCHAR (50)  NULL,
    [RLAPm_FCXMtgInsIncludeFlag]                VARCHAR (50)  NULL,
    [RLAPm_FCXMtgProdMPBusinessID]              VARCHAR (50)  NULL,
    [RLAPm_FCXMtgProductID]                     VARCHAR (50)  NULL,
    [RLAPm_FCXMtgProvderID]                     VARCHAR (50)  NULL,
    [RLAPm_FCXNetLoanAmount]                    VARCHAR (50)  NULL,
    [RLAPm_FCXOriginalMtgAmount]                VARCHAR (50)  NULL,
    [RLAPm_FCXPAndIPaymentAmount]               VARCHAR (50)  NULL,
    [RLAPm_FCXPAndIPaymentAmountMonthly]        VARCHAR (50)  NULL,
    [RLAPm_FCXPaymentFrequency]                 VARCHAR (50)  NULL,
    [RLAPm_FCXPaymentTerm]                      VARCHAR (50)  NULL,
    [RLAPm_FCXPayOffType]                       VARCHAR (50)  NULL,
    [RLAPm_FCXPricingRateInvIndexEffDate]       VARCHAR (50)  NULL,
    [RLAPm_FCXRateInterestRage]                 VARCHAR (50)  NULL,
    [RLAPm_FCXRateDiscount]                     VARCHAR (50)  NULL,
    [RLAPm_FCXRatePremium]                      VARCHAR (50)  NULL,
    [RLAPm_FCXRateBuydownRate]                  VARCHAR (50)  NULL,
    [RLAPm_FCXRateNetRate]                      VARCHAR (50)  NULL,
    [RLAPm_FCXRateGuaranteeLength]              VARCHAR (50)  NULL,
    [RLAPm_FCXRefiAdditionalInfo]               VARCHAR (50)  NULL,
    [RLAPm_FCXRefiBlendedAmort]                 VARCHAR (50)  NULL,
    [RLAPm_FCXRequestedRate]                    VARCHAR (50)  NULL,
    [RLAPm_FCXPrivilegePayment]                 VARCHAR (50)  NULL,
    [RLAPm_FCXPrepaymentOptions]                VARCHAR (50)  NULL,
    [RLAPm_FCXSingleProgressiveType]            VARCHAR (50)  NULL,
    [RLAPm_FCXTotalLoanAmount]                  VARCHAR (50)  NULL,
    [RLAPm_FCXPAndIPaymentAmountQualify]        VARCHAR (50)  NULL,
    [RLAPm_FCXQualifyingGDS]                    VARCHAR (50)  NULL,
    [RLAPm_FCXQualifyingRate]                   VARCHAR (50)  NULL,
    [RLAPm_FCXQualifyingTDS]                    VARCHAR (50)  NULL,
    [RLAPm_FCXQualifyingDetailAmortTerm]        VARCHAR (50)  NULL,
    [RLAPm_FCXQualifyingDetailInterestCompound] VARCHAR (50)  NULL,
    [RLAPm_FCXQualifyingDetailInterestOnlyFlag] VARCHAR (50)  NULL,
    [RLAPm_FCXQualifyingDetailRepaymentType]    VARCHAR (50)  NULL,
    [RLAPm_ExistingMortgageNo]                  VARCHAR (50)  NULL,
    [RLAPm_FCXTermType]                         VARCHAR (50)  NULL,
    [RLAPm_BrokerModel]                         VARCHAR (255) NULL,
    CONSTRAINT [PK_iO_Product_LoanAssetPropertyMortgage] PRIMARY KEY CLUSTERED ([RLAPm_ID] ASC) WITH (FILLFACTOR = 85)
);


GO
CREATE NONCLUSTERED INDEX [IX_iO_Product_LoanAssetPropertyMort_10]
    ON [dbo].[iO_Product_LoanAssetPropertyMortgage]([RLAPm_IDLink_RLAp] ASC, [RLAPm_FCXPayOffType] ASC) WITH (FILLFACTOR = 85);

