CREATE TABLE [dbo].[iO_DNB_ResponseDefaults] (
    [DNBd_ID]                         VARCHAR (40)  NOT NULL,
    [DNBd_Ownership]                  VARCHAR (40)  NULL,
    [DNBd_IDLink_Version]             VARCHAR (40)  NULL,
    [DNBd_IDLink_SCM]                 VARCHAR (40)  NULL,
    [DNBd_IDLink_DNBmr]               VARCHAR (40)  NULL,
    [DNBd_IDLink_Sync]                VARCHAR (40)  NULL,
    [DNBd_SeqNumber]                  BIGINT        NULL,
    [DNBd_SegID]                      VARCHAR (50)  NULL,
    [DNBd_Sequence]                   VARCHAR (50)  NULL,
    [DNBd_AccountTypeCode]            VARCHAR (50)  NULL,
    [DNBd_AccountTypeDesc]            VARCHAR (255) NULL,
    [DNBd_OriginalCreditProvider]     VARCHAR (50)  NULL,
    [DNBd_CurrentCreditProvider]      VARCHAR (50)  NULL,
    [DNBd_OriginalCustomerReference]  VARCHAR (50)  NULL,
    [DNBd_CurrentCustomerReference]   VARCHAR (50)  NULL,
    [DNBd_StatusDesc]                 VARCHAR (255) NULL,
    [DNBd_StatusCode]                 VARCHAR (50)  NULL,
    [DNBd_CreditObligationCode]       VARCHAR (50)  NULL,
    [DNBd_CreditObligationDesc]       VARCHAR (255) NULL,
    [DNBd_Purpose]                    VARCHAR (255) NULL,
    [DNBd_OriginalAmount]             VARCHAR (50)  NULL,
    [DNBd_CurrentAmount]              VARCHAR (50)  NULL,
    [DNBd_LastPaymentDate]            VARCHAR (50)  NULL,
    [DNBd_DateOfDefault]              VARCHAR (50)  NULL,
    [DNBd_OriginalReasonToReportDesc] VARCHAR (255) NULL,
    [DNBd_OriginalReasonToReportCode] VARCHAR (50)  NULL,
    [DNBd_CurrentReasonToReportDesc]  VARCHAR (255) NULL,
    [DNBd_CurrentReasonToReportCode]  VARCHAR (50)  NULL,
    CONSTRAINT [PK_iO_DNB_ResponseDefaults] PRIMARY KEY CLUSTERED ([DNBd_ID] ASC) WITH (FILLFACTOR = 85)
);

