CREATE TABLE [dbo].[iO_EFX_Bankruptcies] (
    [EFXBKP_ID]                              VARCHAR (40) NULL,
    [EFXBKP_Ownership]                       VARCHAR (40) NULL,
    [EFXBKP_Version]                         VARCHAR (40) NULL,
    [EFXBKP_Sync]                            VARCHAR (40) NULL,
    [EFXBKP_Code]                            VARCHAR (40) NULL,
    [EFXBKP_Type]                            INT          NULL,
    [EFXBKP_IDUser]                          INT          NULL,
    [EFXBKP_IDLink_EFXRQ]                    VARCHAR (40) NULL,
    [EFXBKP_IDLink_CMR]                      VARCHAR (40) NULL,
    [EFXBKP_SeqNumber]                       BIGINT       IDENTITY (1, 1) NOT NULL,
    [EFXBKP_IDLink_EFXSBJ]                   VARCHAR (40) NULL,
    [EFXBKP_DateFiled]                       INT          NULL,
    [EFXBKP_CourtId_CustomerNumber]          VARCHAR (10) NULL,
    [EFXBKP_CourtId_Name]                    VARCHAR (30) NULL,
    [EFXBKP_CaseNumberAndTrustee]            INT          NULL,
    [EFXBKP_Type_code]                       VARCHAR (1)  NULL,
    [EFXBKP_Type_description]                VARCHAR (20) NULL,
    [EFXBKP_Filer_code]                      VARCHAR (1)  NULL,
    [EFXBKP_Filer_description]               VARCHAR (20) NULL,
    [EFXBKP_IntentOrDisposition_code]        VARCHAR (1)  NULL,
    [EFXBKP_IntentOrDisposition_description] VARCHAR (45) NULL,
    [EFXBKP_Date]                            INT          NULL,
    [EFXBKP_LiabilityAmount]                 INT          NULL,
    [EFXBKP_AssetAmount]                     INT          NULL,
    [EFXBKP_UpdateSource_code]               VARCHAR (1)  NULL,
    [EFXBKP_UpdateSource_description]        VARCHAR (20) NULL,
    [EFXBKP_NarrativeCode_1]                 VARCHAR (2)  NULL,
    [EFXBKP_NarrativeCode_2]                 VARCHAR (2)  NULL,
    [EFXBKP_Note]                            TEXT         NULL
);

