CREATE TABLE [dbo].[iO_EFX_TradeLines] (
    [EFXTrd_ID]                        VARCHAR (40) NULL,
    [EFXTrd_Ownership]                 VARCHAR (40) NULL,
    [EFXTrd_Version]                   VARCHAR (40) NULL,
    [EFXTrd_Sync]                      VARCHAR (40) NULL,
    [EFXTrd_Code]                      VARCHAR (40) NULL,
    [EFXTrd_Type]                      INT          NULL,
    [EFXTrd_IDUser]                    INT          NULL,
    [EFXTrd_IDLink_EFXRQ]              VARCHAR (40) NULL,
    [EFXTrd_SeqNumber]                 BIGINT       IDENTITY (1, 1) NOT NULL,
    [EFXTrd_IDLink_EFXSBJ]             VARCHAR (40) NULL,
    [EFXTrd_DateReported]              INT          NULL,
    [EFXTrd_CreditorId_CustomerNumber] VARCHAR (10) NULL,
    [EFXTrd_CreditorId_Name]           VARCHAR (30) NULL,
    [EFXTrd_ParsedTelephone_AreaCode]  INT          NULL,
    [EFXTrd_ParsedTelephone_Number]    VARCHAR (8)  NULL,
    [EFXTrd_ParsedTelephone_Extension] INT          NULL,
    [EFXTrd_AccountNumber]             VARCHAR (15) NULL,
    [EFXTrd_AccountNumber_mnemonic]    VARCHAR (6)  NULL,
    [EFXTrd_Association_code]          VARCHAR (1)  NULL,
    [EFXTrd_Association_description]   VARCHAR (20) NULL,
    [EFXTrd_HighCreditAmount]          INT          NULL,
    [EFXTrd_PaymentTermAmount]         INT          NULL,
    [EFXTrd_BalanceAmount]             INT          NULL,
    [EFXTrd_PastDueAmount]             INT          NULL,
    [EFXTrd_pastDuePeriodNumber]       INT          NULL,
    [EFXTrd_MonthsReviewed]            INT          NULL,
    [EFXTrd_DateOpened]                INT          NULL,
    [EFXTrd_DateLastActivityOrPayment] INT          NULL,
    [EFXTrd_PortfolioType_code]        VARCHAR (1)  NULL,
    [EFXTrd_PortfolioType_description] VARCHAR (20) NULL,
    [EFXTrd_PaymentRate_code]          VARCHAR (1)  NULL,
    [EFXTrd_PaymentRate_description]   VARCHAR (85) NULL,
    [EFXTrd_Status_code]               VARCHAR (1)  NULL,
    [EFXTrd_Status_description]        VARCHAR (85) NULL,
    [EFXTrd_Count30DayPastDue]         INT          NULL,
    [EFXTrd_Count60DayPastDue]         INT          NULL,
    [EFXTrd_Count90DayPastDue]         INT          NULL,
    [EFXTrd_UpdateSource_code]         VARCHAR (1)  NULL,
    [EFXTrd_UpdateSource_description]  VARCHAR (20) NULL,
    [EFXTrd_Note]                      TEXT         NULL
);

