CREATE TABLE [dbo].[iO_EFX_LegalItems] (
    [EFXLEG_ID]                       VARCHAR (40) NULL,
    [EFXLEG_Ownership]                VARCHAR (40) NULL,
    [EFXLEG_Version]                  VARCHAR (40) NULL,
    [EFXLEG_Sync]                     VARCHAR (40) NULL,
    [EFXLEG_Code]                     VARCHAR (40) NULL,
    [EFXLEG_Type]                     INT          NULL,
    [EFXLEG_IDUser]                   INT          NULL,
    [EFXLEG_IDLink_EFXRQ]             VARCHAR (40) NULL,
    [EFXLEG_IDLink_CMR]               VARCHAR (40) NULL,
    [EFXLEG_SeqNumber]                BIGINT       IDENTITY (1, 1) NOT NULL,
    [EFXLEG_IDLink_EFXSBJ]            VARCHAR (40) NULL,
    [EFXLEG_LegalItem_code]           VARCHAR (2)  NULL,
    [EFXLEG_LegalItem_description]    VARCHAR (40) NULL,
    [EFXLEG_DateFiled]                INT          NULL,
    [EFXLEG_CourtID_CustomerNumber]   VARCHAR (10) NULL,
    [EFXLEG_CourtID_Name]             VARCHAR (30) NULL,
    [EFXLEG_CaseNumber]               VARCHAR (42) NULL,
    [EFXLEG_Status_code]              VARCHAR (1)  NULL,
    [EFXLEG_Status_description]       VARCHAR (21) NULL,
    [EFXLEG_DateSatisfied]            INT          NULL,
    [EFXLEG_Amount]                   INT          NULL,
    [EFXLEG_VerificationDate]         INT          NULL,
    [EFXLEG_Defendant]                VARCHAR (42) NULL,
    [EFXLEG_Plaintiff]                VARCHAR (40) NULL,
    [EFXLEG_LawyerNameAddress]        VARCHAR (60) NULL,
    [EFXLEG_UpdateSource_code]        VARCHAR (1)  NULL,
    [EFXLEG_UpdateSource_description] VARCHAR (20) NULL,
    [EFXLEG_NarrativeCode_1]          VARCHAR (2)  NULL,
    [EFXLEG_NarrativeCode_2]          VARCHAR (2)  NULL,
    [EFXLEG_Note]                     TEXT         NULL
);

