CREATE TABLE [dbo].[iO_EFX_Scores] (
    [EFXSC_ID]                     VARCHAR (40) NULL,
    [EFXSC_Ownership]              VARCHAR (40) NULL,
    [EFXSC_Version]                VARCHAR (40) NULL,
    [EFXSC_Sync]                   VARCHAR (40) NULL,
    [EFXSC_Code]                   VARCHAR (40) NULL,
    [EFXSC_Type]                   INT          NULL,
    [EFXSC_IDUser]                 INT          NULL,
    [EFXSC_IDLink_EFXRQ]           VARCHAR (40) NULL,
    [EFXSC_IDLink_CMR]             VARCHAR (40) NULL,
    [EFXSC_SeqNumber]              BIGINT       IDENTITY (1, 1) NOT NULL,
    [EFXSC_IDLink_EFXSBJ]          VARCHAR (40) NULL,
    [EFXSC_productType]            VARCHAR (4)  NULL,
    [EFXSC_productId]              INT          NULL,
    [EFXSC_description]            VARCHAR (20) NULL,
    [EFXSC_VersionNumber]          VARCHAR (3)  NULL,
    [EFXSC_ModelId]                VARCHAR (1)  NULL,
    [EFXSC_ScoreNumber]            INT          NULL,
    [EFXSC_ScoreIndicator]         VARCHAR (1)  NULL,
    [EFXSC_SignIndicator]          VARCHAR (1)  NULL,
    [EFXSC_ScoreValue]             VARCHAR (5)  NULL,
    [EFXSC_ScoreNarrative]         VARCHAR (70) NULL,
    [EFXSC_ScoreAttribute]         VARCHAR (30) NULL,
    [EFXSC_identifier]             VARCHAR (30) NULL,
    [EFXSC_AttributeValue]         VARCHAR (30) NULL,
    [EFXSC_Reason_code]            VARCHAR (30) NULL,
    [EFXSC_Reason_description]     VARCHAR (70) NULL,
    [EFXSC_RejectCode_code]        VARCHAR (5)  NULL,
    [EFXSC_RejectCode_description] VARCHAR (70) NULL,
    [EFXSC_Note]                   TEXT         NULL
);

