CREATE TABLE [dbo].[iO_FCX_ApplicantGroup_Applicant] (
    [FCXaa_ID]                      VARCHAR (40) NOT NULL,
    [FCXaa_IDLink_Ownership]        VARCHAR (40) NULL,
    [FCXaa_IDLink_Version]          VARCHAR (40) NULL,
    [FCXaa_IDLink_Sync]             VARCHAR (40) NULL,
    [FCXaa_IDLink_Code]             VARCHAR (40) NULL,
    [FCXaa_IDLink_SCM]              VARCHAR (50) NULL,
    [FCXaa_IDLink_FCXa]             VARCHAR (50) NULL,
    [FCXaa_SeqNumber]               BIGINT       IDENTITY (1, 1) NOT NULL,
    [FCXaa_DOB]                     VARCHAR (50) NULL,
    [FCXaa_Email]                   VARCHAR (50) NULL,
    [FCXaa_Language]                VARCHAR (50) NULL,
    [FCXaa_MaritalStatus]           VARCHAR (50) NULL,
    [FCXaa_Salutation]              VARCHAR (50) NULL,
    [FCXaa_FirstName]               VARCHAR (50) NULL,
    [FCXaa_MiddleName]              VARCHAR (50) NULL,
    [FCXaa_LastName]                VARCHAR (50) NULL,
    [FCXaa_Suffix]                  VARCHAR (50) NULL,
    [FCXaa_NumberOfDependants]      VARCHAR (50) NULL,
    [FCXaa_PreferredContactMethod]  VARCHAR (50) NULL,
    [FCXaa_SocialInsuranceNumber]   VARCHAR (50) NULL,
    [FCXaa_Solicitation]            VARCHAR (50) NULL,
    [FCXaa_BankruptcyStatus]        VARCHAR (50) NULL,
    [FCXaa_CitizenshipType]         VARCHAR (50) NULL,
    [FCXaa_ClientReferenceNumber]   VARCHAR (50) NULL,
    [FCXaa_CreditScore]             VARCHAR (50) NULL,
    [FCXaa_EmployeeNumber]          VARCHAR (50) NULL,
    [FCXaa_ExistingClient]          VARCHAR (50) NULL,
    [FCXaa_FirstTimeBuyer]          VARCHAR (50) NULL,
    [FCXaa_Gender]                  VARCHAR (50) NULL,
    [FCXaa_IsEmployee]              VARCHAR (50) NULL,
    [FCXaa_PairOrder]               VARCHAR (50) NULL,
    [FCXaa_PrimaryApplicationFlag]  VARCHAR (50) NULL,
    [FCXaa_RelationshipToApplicant] VARCHAR (50) NULL,
    [FCXaa_Smoker]                  VARCHAR (50) NULL
);

