CREATE TABLE [dbo].[iO_MOR_CustomerVersions] (
    [MORcv_ID]                      VARCHAR (40)  NULL,
    [MORcv_Ownership]               VARCHAR (50)  NULL,
    [MORcv_Version]                 VARCHAR (10)  NULL,
    [MORcv_Sync]                    VARCHAR (10)  NULL,
    [MORcv_Code]                    VARCHAR (10)  NULL,
    [MORcv_Type]                    VARCHAR (10)  NULL,
    [MORcv_IDLink_MORreq]           VARCHAR (40)  NULL,
    [MORcv_CORRESPONDENCELANGUAGE]  INT           NULL,
    [MORcv_DATEOFBIRTH]             SMALLDATETIME NULL,
    [MORcv_TITLE]                   INT           NULL,
    [MORcv_CUSTOMERNUMBER]          VARCHAR (12)  NULL,
    [MORcv_SURNAME]                 VARCHAR (40)  NULL,
    [MORcv_FIRSTFORENAME]           VARCHAR (40)  NULL,
    [MORcv_SECONDFORENAME]          VARCHAR (30)  NULL,
    [MORcv_OTHERFORENAME]           VARCHAR (30)  NULL,
    [MORcv_CORRESPONDENCENAME]      VARCHAR (200) NULL,
    [MORcv_CUSTOMERROLETYPE]        INT           NULL,
    [MORcv_UPDATEFLAG]              INT           NULL,
    [MORcv_OWNERROLEINRELATIONSHIP] INT           NULL,
    [MORcv_MEMBEROFSTAFF]           BIT           NULL,
    [MORcv_LENDERREFERENCE]         VARCHAR (30)  NULL,
    [MORcv_CONTACTEMAILADDRESS1]    VARCHAR (100) NULL,
    [MORcv_CONTACTEMAILADDRESS2]    VARCHAR (100) NULL,
    [MORcv_SOCIALINSURANCENUMBER]   CHAR (9)      NULL,
    [MORcv_MARITALSTATUS]           INT           NULL,
    [MORcv_NUMBEROFDEPENDENTS]      TINYINT       NULL,
    [MORcv_CARESIDENTINDICATOR]     BIT           NULL,
    [MORcv_RESIDENTTYPE]            INT           NULL,
    [MORcv_REPORTDATE]              SMALLDATETIME NULL,
    [MORcv_BEACONSCORE]             SMALLINT      NULL,
    [MORcv_TERMHISTORY]             SMALLINT      NULL,
    [MORcv_TOTALBALANCES]           DECIMAL (18)  NULL,
    [MORcv_TMTHLYPYMNTS]            DECIMAL (18)  NULL,
    [MORcv_NUMBEROFR0]              SMALLINT      NULL,
    [MORcv_NUMBEROFI0]              SMALLINT      NULL,
    [MORcv_NUMBEROFO0]              SMALLINT      NULL,
    [MORcv_NUMBEROFM0]              SMALLINT      NULL,
    [MORcv_NUMBEROFR1]              SMALLINT      NULL,
    [MORcv_NUMBEROFI1]              SMALLINT      NULL,
    [MORcv_NUMBEROFO1]              SMALLINT      NULL,
    [MORcv_NUMBEROFM1]              SMALLINT      NULL,
    [MORcv_NUMBEROFR2]              SMALLINT      NULL,
    [MORcv_NUMBEROFI2]              SMALLINT      NULL,
    [MORcv_NUMBEROFO2]              SMALLINT      NULL,
    [MORcv_NUMBEROFM2]              SMALLINT      NULL,
    [MORcv_NUMBEROFR3]              SMALLINT      NULL,
    [MORcv_NUMBEROFI3]              SMALLINT      NULL,
    [MORcv_NUMBEROFO3]              SMALLINT      NULL,
    [MORcv_NUMBEROFM3]              SMALLINT      NULL,
    [MORcv_NUMBEROFR4]              SMALLINT      NULL,
    [MORcv_NUMBEROFI4]              SMALLINT      NULL,
    [MORcv_NUMBEROFO4]              SMALLINT      NULL,
    [MORcv_NUMBEROFM4]              SMALLINT      NULL,
    [MORcv_NUMBEROFR5]              SMALLINT      NULL,
    [MORcv_NUMBEROFI5]              SMALLINT      NULL,
    [MORcv_NUMBEROFO5]              SMALLINT      NULL,
    [MORcv_NUMBEROFM5]              SMALLINT      NULL,
    [MORcv_NUMBEROFR6]              SMALLINT      NULL,
    [MORcv_NUMBEROFI6]              SMALLINT      NULL,
    [MORcv_NUMBEROFO6]              SMALLINT      NULL,
    [MORcv_NUMBEROFM6]              SMALLINT      NULL,
    [MORcv_NUMBEROFR7]              SMALLINT      NULL,
    [MORcv_NUMBEROFI7]              SMALLINT      NULL,
    [MORcv_NUMBEROFO7]              SMALLINT      NULL,
    [MORcv_NUMBEROFM7]              SMALLINT      NULL,
    [MORcv_NUMBEROFR8]              SMALLINT      NULL,
    [MORcv_NUMBEROFI8]              SMALLINT      NULL,
    [MORcv_NUMBEROFO8]              SMALLINT      NULL,
    [MORcv_NUMBEROFM8]              SMALLINT      NULL,
    [MORcv_NUMBEROFR9]              SMALLINT      NULL,
    [MORcv_NUMBEROFI9]              SMALLINT      NULL,
    [MORcv_NUMBEROFO9]              SMALLINT      NULL,
    [MORcv_NUMBEROFM9]              SMALLINT      NULL,
    [MORcv_BANKRUPTCY]              SMALLINT      NULL,
    [MORcv_BNKRPTPROP]              SMALLINT      NULL,
    [MORcv_LEGALITEMS]              SMALLINT      NULL,
    [MORcv_COLLECTIONS]             SMALLINT      NULL,
    [MORcv_GARNISH]                 SMALLINT      NULL,
    [MORcv_AKAREFERENCE]            SMALLINT      NULL,
    [MORcv_INVALIDSIN]              SMALLINT      NULL,
    [MORcv_SUFUNEQUAL]              SMALLINT      NULL,
    [MORcv_SINMISMATCH]             SMALLINT      NULL,
    [MORcv_DOBMISMATCH]             SMALLINT      NULL,
    [MORcv_CDATAEXISTS]             BIT           NULL,
    [MORcv_ENCODE]                  INT           NULL,
    [MORcv_COMPRESSION]             INT           NULL,
    [MORcv_HTMLREPORT]              VARCHAR (MAX) NULL
);

