CREATE TABLE [dbo].[iO_MEM_Application] (
    [MEMapp_ID]                        VARCHAR (40)  NULL,
    [MEMapp_Ownership]                 VARCHAR (40)  NULL,
    [MEMapp_IDLink_Version]            VARCHAR (40)  NULL,
    [MEMapp_IDLink_Sync]               VARCHAR (40)  NULL,
    [MEMapp_IDLink_CMR]                VARCHAR (40)  NULL,
    [MEMapp_IDLink_RMR]                VARCHAR (40)  NULL,
    [MEMapp_ApplyDate]                 DATETIME      NULL,
    [MEMapp_LoanAmount]                INT           NULL,
    [MEMapp_LoanTerm]                  INT           NULL,
    [MEMapp_Title]                     VARCHAR (6)   NULL,
    [MEMapp_FirstName]                 VARCHAR (50)  NULL,
    [MEMapp_LastName]                  VARCHAR (50)  NULL,
    [MEMapp_EMailAddress]              VARCHAR (254) NULL,
    [MEMapp_DateOfBirth]               DATETIME      NULL,
    [MEMapp_HomePhone]                 VARCHAR (11)  NULL,
    [MEMapp_MobilePhone]               VARCHAR (11)  NULL,
    [MEMapp_WorkPhone]                 VARCHAR (11)  NULL,
    [MEMapp_ResidentialStatus]         VARCHAR (40)  NULL,
    [MEMapp_PostCode]                  VARCHAR (8)   NULL,
    [MEMapp_FlatNumber]                VARCHAR (4)   NULL,
    [MEMapp_HouseNameOrNumber]         VARCHAR (20)  NULL,
    [MEMapp_AddressLine1]              VARCHAR (100) NULL,
    [MEMapp_AddressLine2]              VARCHAR (100) NULL,
    [MEMapp_City]                      VARCHAR (50)  NULL,
    [MEMapp_County]                    VARCHAR (40)  NULL,
    [MEMapp_EmploymentIndustry]        VARCHAR (40)  NULL,
    [MEMapp_CompanyName]               VARCHAR (100) NULL,
    [MEMapp_PrimaryIncome]             VARCHAR (40)  NULL,
    [MEMapp_PayFrequency]              VARCHAR (40)  NULL,
    [MEMapp_NetMonthlyPay]             VARCHAR (10)  NULL,
    [MEMapp_NextPayDate]               DATETIME      NULL,
    [MEMapp_DebitCardType]             VARCHAR (30)  NULL,
    [MEMapp_DirectDeposit]             BIT           NULL,
    [MEMapp_BankWith]                  VARCHAR (100) NULL,
    [MEMapp_MonthlyRepaymentDay]       INT           NULL,
    [MEMapp_PersonalData]              BIT           NULL,
    [MEMapp_Marketing]                 BIT           NULL,
    [MEMapp_SECCI_Date]                DATETIME      NULL,
    [MEMapp_SECCI_Method]              VARCHAR (128) NULL,
    [MEMapp_DirectDebitMandate_Date]   DATETIME      NULL,
    [MEMapp_DirectDebitMandate_Method] VARCHAR (128) NULL,
    [MEMapp_LoanAgreement_Date]        DATETIME      NULL,
    [MEMapp_LoanAgreement_Method]      VARCHAR (128) NULL,
    [MEMapp_Notes]                     TEXT          NULL,
    [MEMapp_Status]                    VARCHAR (20)  NULL
);

