CREATE TABLE [dbo].[iO_NextGen_ImportDefaults] (
    [NGI_ID]                          VARCHAR (40) NOT NULL,
    [NGI_Ownership]                   VARCHAR (40) NOT NULL,
    [NGI_SeqNumber]                   INT          IDENTITY (1, 1) NOT NULL,
    [NGI_IDLink_Version]              VARCHAR (40) NULL,
    [NGI_IDLink_Sync]                 VARCHAR (40) NULL,
    [NGI_ForeignKey_Application]      VARCHAR (40) NULL,
    [NGI_ForeignKey_Client]           VARCHAR (40) NULL,
    [NGI_ForeignKey_Loan]             VARCHAR (40) NULL,
    [NGI_Status_Received]             VARCHAR (40) NULL,
    [NGI_Status_Approved]             VARCHAR (40) NULL,
    [NGI_Status_Settled]              VARCHAR (40) NULL,
    [NGI_Status_Current]              VARCHAR (40) NULL,
    [NGI_ClientClassIndividual]       VARCHAR (40) NULL,
    [NGI_ClientClassCompany]          VARCHAR (40) NULL,
    [NGI_DrawdownTransaction]         VARCHAR (40) NULL,
    [NGI_JointRelationshipKey]        VARCHAR (40) NULL,
    [NGI_Balance_Principle]           VARCHAR (40) NULL,
    [NGI_Balance_Application]         VARCHAR (40) NULL,
    [NGI_Balance_Approval]            VARCHAR (40) NULL,
    [NGI_Type]                        INT          NULL,
    [NGI_IDUser]                      INT          NULL,
    [NGI_Note]                        TEXT         NULL,
    [NGI_ClientAssociation_Primary]   VARCHAR (40) NULL,
    [NGI_ClientAssociation_Borrower]  VARCHAR (40) NULL,
    [NGI_ClientAssociation_Guarantor] VARCHAR (40) NULL,
    [NGI_PaymentCalculation]          VARCHAR (40) NULL,
    [NGI_DisbursementTransaction]     VARCHAR (40) NULL
);

