CREATE TABLE [dbo].[iO_Product_LoanAssetPTYExpense] (
    [RLAe_ID]             VARCHAR (40) NOT NULL,
    [RLAe_Ownership]      VARCHAR (40) NULL,
    [RLAe_IDLink_Sync]    VARCHAR (40) NULL,
    [RLAe_IDLink_RLAp]    VARCHAR (40) NULL,
    [RLAe_RentBoard]      FLOAT (53)   NULL,
    [RLAe_Maintenace]     FLOAT (53)   NULL,
    [RLAe_ChildSupport]   FLOAT (53)   NULL,
    [RLAe_Other]          FLOAT (53)   NULL,
    [RLAe_IDLink_Version] VARCHAR (40) NULL,
    [RLAe_SeqNumber]      BIGINT       NULL,
    [RLAe_IDLink_XFPE]    VARCHAR (40) NULL,
    [RLAe_IDUser]         INT          NULL,
    [RLAe_IDLink_CMR]     VARCHAR (40) NULL,
    [RLAe_IDLink_XLBo]    VARCHAR (40) NULL,
    [RLAe_IDLink_XFR]     VARCHAR (40) NULL,
    [RLAe_LoanBSB]        VARCHAR (40) NULL,
    [RLAe_LoanAccount]    VARCHAR (40) NULL,
    [RLAe_Value]          FLOAT (53)   NULL,
    [RLAe_ValuePerYear]   FLOAT (53)   NULL,
    [RLAe_Note]           TEXT         NULL,
    [RLAe_Maintenance]    FLOAT (53)   NULL,
    [RLAe_PEGA_HPI]       FLOAT (53)   NULL,
    [RLAe_PEGA_Total]     FLOAT (53)   NULL,
    [RLAe_IDLink_RSP]     VARCHAR (40) NULL,
    [RLAe_Type]           INT          NULL,
    CONSTRAINT [PK_iO_Product_LoanAssetPTYExpense] PRIMARY KEY CLUSTERED ([RLAe_ID] ASC) WITH (FILLFACTOR = 85)
);

