CREATE TABLE [dbo].[iO_Product_SecurityPTY_Log] (
    [RSP_ID]                      VARCHAR (40)  NOT NULL,
    [RSP_Ownership]               VARCHAR (40)  NOT NULL,
    [RSP_IDLink_Version]          VARCHAR (40)  NULL,
    [RSP_IDLink_Sync]             VARCHAR (40)  NULL,
    [RSP_IDLink_RMR]              VARCHAR (40)  NULL,
    [RSP_IDLink_RSE]              VARCHAR (40)  NULL,
    [RSP_IDLink_CAD]              VARCHAR (40)  NULL,
    [RSP_IDLink_StreetType]       VARCHAR (40)  NULL,
    [RSP_IDLink_Country]          VARCHAR (40)  NULL,
    [RSP_IDLink_XRTy]             VARCHAR (40)  NULL,
    [RSP_IDLink_XRTu]             VARCHAR (40)  NULL,
    [RSP_IDLink_XRTt]             VARCHAR (40)  NULL,
    [RSP_IDLink_XRTp]             VARCHAR (40)  NULL,
    [RSP_IDLink_XRTgt]            VARCHAR (40)  NULL,
    [RSP_IDLink_XRTgc]            VARCHAR (40)  NULL,
    [RSP_IDLink_XRTht]            VARCHAR (40)  NULL,
    [RSP_IDLink_XRTus]            VARCHAR (40)  NULL,
    [RSP_IDLink_XRTul]            VARCHAR (40)  NULL,
    [RSP_IDLink_XRTc]             VARCHAR (40)  NULL,
    [RSP_IDLink_XRTz]             VARCHAR (40)  NULL,
    [RSP_SeqNumber]               BIGINT        IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [RSP_Type]                    INT           NULL,
    [RSP_IDUser]                  INT           NULL,
    [RSP_PurchasePrice]           FLOAT (53)    NULL,
    [RSP_EstimatedValue]          FLOAT (53)    NULL,
    [RSP_PropertyName]            VARCHAR (255) NULL,
    [RSP_UnitNumber]              VARCHAR (50)  NULL,
    [RSP_StreetNumber]            VARCHAR (50)  NULL,
    [RSP_StreetName]              VARCHAR (255) NULL,
    [RSP_City]                    VARCHAR (255) NULL,
    [RSP_State]                   VARCHAR (255) NULL,
    [RSP_PostCode]                VARCHAR (10)  NULL,
    [RSP_Direction]               VARCHAR (MAX) NULL,
    [RSP_ActionType]              INT           NULL,
    [RSP_AccessName]              TEXT          NULL,
    [RSP_AccessNumberWork]        VARCHAR (50)  NULL,
    [RSP_AccessNumberHome]        VARCHAR (50)  NULL,
    [RSP_AccessNumberMobile]      VARCHAR (50)  NULL,
    [RSP_AccessNote]              TEXT          NULL,
    [RSP_NameOnDeed]              TEXT          NULL,
    [RSP_BookNumber]              VARCHAR (50)  NULL,
    [RSP_CertID]                  VARCHAR (50)  NULL,
    [RSP_CT]                      VARCHAR (50)  NULL,
    [RSP_FolioNumber]             VARCHAR (50)  NULL,
    [RSP_LotNo]                   VARCHAR (50)  NULL,
    [RSP_LpDp]                    VARCHAR (50)  NULL,
    [RSP_Number]                  VARCHAR (50)  NULL,
    [RSP_Parish]                  VARCHAR (50)  NULL,
    [RSP_County]                  VARCHAR (50)  NULL,
    [RSP_SubDiv]                  VARCHAR (50)  NULL,
    [RSP_VolNo]                   VARCHAR (50)  NULL,
    [RSP_TenantName]              VARCHAR (255) NULL,
    [RSP_GrossWeeklyRent]         FLOAT (53)    NULL,
    [RSP_RegistrationNumber]      VARCHAR (50)  NULL,
    [RSP_DateRegistered]          DATETIME      NULL,
    [RSP_StampedTo]               VARCHAR (512) NULL,
    [RSP_AccessNumber]            TEXT          NULL,
    [RSP_DateDischarged]          DATETIME      NULL,
    [RSP_PropertyZoning]          VARCHAR (MAX) NULL,
    [RSP_CurrentMarketValue]      FLOAT (53)    NULL,
    [RSP_AccessContactType]       TEXT          NULL,
    [RSP_InactiveSecurity]        BIT           NULL,
    [RSP_LandSize]                VARCHAR (50)  NULL,
    [RSP_StudioSize]              VARCHAR (50)  NULL,
    [RSP_EstRentalValue]          FLOAT (53)    NULL,
    [RSP_LandValue]               FLOAT (53)    NULL,
    [RSP_ValuationPostcode]       VARCHAR (50)  NULL,
    [RSP_BedroomCount]            INT           NULL,
    [RSP_BathroomCount]           INT           NULL,
    [RSP_KitchenCount]            INT           NULL,
    [RSP_FloorCount]              INT           NULL,
    [RSP_UnitCount]               INT           NULL,
    [RSP_HeatingValue]            FLOAT (53)    NULL,
    [RSP_HeatingType]             VARCHAR (MAX) NULL,
    [RSP_IsServiceOrManaged]      BIT           NULL,
    [RSP_SuiteNumber]             VARCHAR (50)  NULL,
    [RSP_FloorNumber]             VARCHAR (50)  NULL,
    [RSP_HighRisk]                BIT           NULL,
    [RSP_HighRiskOverride]        BIT           NULL,
    [RSP_LocationTypeCode]        VARCHAR (50)  NULL,
    [RSP_BuilderName]             VARCHAR (255) NULL,
    [RSP_FeesIncludeHeatFlag]     BIT           NULL,
    [RSP_IncludesTDS]             BIT           NULL,
    [RSP_InsulatedWithUFFI]       BIT           NULL,
    [RSP_LegalLine1]              VARCHAR (MAX) NULL,
    [RSP_LegalLine2]              VARCHAR (MAX) NULL,
    [RSP_LegalLine3]              VARCHAR (MAX) NULL,
    [RSP_MLSListing]              BIT           NULL,
    [RSP_Note]                    TEXT          NULL,
    [RSP_IDLink_XRTvi]            VARCHAR (40)  NULL,
    [RSP_IDLink_XRTro]            VARCHAR (40)  NULL,
    [RSP_IDLink_XRTs]             VARCHAR (40)  NULL,
    [RSP_IDLink_XRTw]             VARCHAR (40)  NULL,
    [RSP_IDLink_XRTl]             VARCHAR (40)  NULL,
    [RSP_IDLink_XRPT]             VARCHAR (40)  NULL,
    [RSP_IsPrimary]               BIT           NULL,
    [RSP_AppraisalRequested]      BIT           NULL,
    [RSP_AppraisalDate]           VARCHAR (50)  NULL,
    [RSP_AgeOfStructure]          INT           NULL,
    [RSP_SubjectProperty]         BIT           NULL,
    [RSP_YearBuilt]               INT           NULL,
    [RSP_TaxationYear]            INT           NULL,
    [RSP_OriginalPurchasePrice]   FLOAT (53)    NULL,
    [RSP_OriginalPurchaseDate]    VARCHAR (50)  NULL,
    [RSP_AnnualIncomeAmt]         FLOAT (53)    NULL,
    [RSP_IncomeDesc]              VARCHAR (MAX) NULL,
    [RSP_IncomePctGDS]            FLOAT (53)    NULL,
    [RSP_IncomePctTDS]            FLOAT (53)    NULL,
    [RSP_IDLink_XFR]              VARCHAR (40)  NULL,
    [RSP_IDLink_XIN]              VARCHAR (40)  NULL,
    [RSP_IncomeAmt]               FLOAT (53)    NULL,
    [RSP_FISBO]                   BIT           NULL,
    [RSP_EnvironmentalRisk]       INT           NULL,
    [RSP_IsEnergyEfficient]       BIT           NULL,
    [RSP_PurchaseLtv]             FLOAT (53)    NULL,
    [RSP_OriginalLtv]             FLOAT (53)    NULL,
    [RSP_FireInsuranceNo]         VARCHAR (MAX) NULL,
    [RSP_TitleInsuranceNo]        VARCHAR (MAX) NULL,
    [RSP_PreviousSaleDate]        VARCHAR (50)  NULL,
    [RSP_FireInsuranceExpiryDate] VARCHAR (50)  NULL,
    [RSP_FireInsuranceCompany]    VARCHAR (50)  NULL,
    [RSP_TitleInsuranceCompany]   VARCHAR (50)  NULL,
    [RSP_StateRegion]             VARCHAR (50)  NULL,
    [Modified Date]               DATETIME      NULL,
    [User ID]                     NVARCHAR (40) NULL,
    CONSTRAINT [PK_iO_Product_SceurityPTY_Log] PRIMARY KEY CLUSTERED ([RSP_ID] ASC) WITH (FILLFACTOR = 85)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Primary Key.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'iO_Product_SecurityPTY_Log', @level2type = N'COLUMN', @level2name = N'RSP_ID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Redundant.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'iO_Product_SecurityPTY_Log', @level2type = N'COLUMN', @level2name = N'RSP_Ownership';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Used to compare records in Replication process.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'iO_Product_SecurityPTY_Log', @level2type = N'COLUMN', @level2name = N'RSP_IDLink_Version';

