CREATE TABLE [dbo].[iO_Product_CheckListAssessment] (
    [RCA_ID]                                 VARCHAR (40)  NOT NULL,
    [RCA_Ownership]                          VARCHAR (40)  NULL,
    [RCA_IDLink_Version]                     VARCHAR (40)  NULL,
    [RCA_IDLink_Sync]                        VARCHAR (40)  NULL,
    [RCA_IDLink_RMR]                         VARCHAR (40)  NULL,
    [RCA_OngoingEmployment]                  INT           NULL,
    [RCA_EmployeeIsOnContract]               INT           NULL,
    [RCA_ContractExpiryDate]                 DATETIME      NULL,
    [RCA_EmployeeIsOnProbation]              INT           NULL,
    [RCA_ProbationExpiry]                    DATETIME      NULL,
    [RCA_EmploymentConfirmed]                INT           NULL,
    [RCA_ProofOfIncomeRcvd]                  INT           NULL,
    [RCA_EmploymentIsAcceptable]             INT           NULL,
    [RCA_EmploymentABNSearch]                VARCHAR (MAX) NULL,
    [RCA_EmploymentWhitePagesSearch]         INT           NULL,
    [RCA_PersonalDetailsMatchPaySlip]        INT           NULL,
    [RCA_PreviousEmpConfirmed]               INT           NULL,
    [RCA_ResidenceConfirmed]                 INT           NULL,
    [RCA_ProofOfResidenceRcvd]               INT           NULL,
    [RCA_ResidenceIsAcceptable]              INT           NULL,
    [RCA_ResidenceWhitePagesSearch]          INT           NULL,
    [RCA_RateNotice]                         INT           NULL,
    [RCA_LeaseAgreement]                     INT           NULL,
    [RCA_ResponsibleTennant]                 INT           NULL,
    [RCA_PrivacyHasBeenSigned]               INT           NULL,
    [RCA_VedaCheckRequired]                  INT           NULL,
    [RCA_CreditHistoryAcceptable]            INT           NULL,
    [RCA_ConfirmAllNumbersConnected]         INT           NULL,
    [RCA_ExistingCustomer]                   INT           NULL,
    [RCA_BorrowerDetailsConfirmed]           INT           NULL,
    [RCA_BorrowerDetailsByWhitePages]        INT           NULL,
    [RCA_ThreeMonthsOfStatements]            INT           NULL,
    [RCA_AdditionalLoanStatements]           INT           NULL,
    [RCA_CreditCardStatements]               INT           NULL,
    [RCA_DealerTaxInvoice]                   INT           NULL,
    [RCA_ContractOfSale]                     INT           NULL,
    [RCA_BankAccountVerified]                INT           NULL,
    [RCA_PurchasersDetsVerifiedOnTaxInvoice] INT           NULL,
    [RCA_RoadWorthyCertificate]              INT           NULL,
    [RCA_ProofRegInSellersName]              INT           NULL,
    [RCA_SellersDriversLicence]              INT           NULL,
    [RCA_ProofSellersBankDetails]            INT           NULL,
    [RCA_SignedTaxInvoice]                   INT           NULL,
    [RCA_HaveInsuranceDetsBeenUpdated]       INT           NULL,
    [RCA_SecurityIsOK]                       INT           NULL,
    [RCA_Note]                               TEXT          NULL,
    [RCA_NoteRes]                            TEXT          NULL,
    [RCA_C1WPListed]                         INT           NULL,
    [RCA_C2WPListed]                         INT           NULL,
    [RCA_C1SpokeTo]                          INT           NULL,
    [RCA_C2SpokeTo]                          INT           NULL,
    [RCA_C1DetailsConfirmed]                 INT           NULL,
    [RCA_C2DetailsConfirmed]                 INT           NULL,
    [RCA_C1Note]                             TEXT          NULL,
    [RCA_C2Note]                             TEXT          NULL,
    [RCA_BorrowerNote]                       TEXT          NULL,
    [RCA_UnsuitableRegulations]              INT           NULL,
    [RCA_ComplyWithObligations]              INT           NULL,
    [RCA_ComplyWithNoHardship]               INT           NULL,
    [RCA_LikelinessOfEventsToStopPayments]   INT           NULL,
    [RCA_ResponseFactor]                     INT           NULL,
    [RCA_LoansRepaid]                        INT           NULL,
    [RCA_LoansRepaidWithinTerm]              INT           NULL,
    [RCA_SufficientDisposableIncome]         INT           NULL,
    [RCA_CentrelinkRepayments]               INT           NULL,
    [RCA_CustomerGrossIncome]                INT           NULL,
    [RCA_SmallAmountCreditContacts]          INT           NULL,
    [RCA_DefaultofSmallAmountCreditContacts] INT           NULL,
    [RCA_AllDocumentationProvided]           INT           NULL,
    [RCA_InformationVerified]                INT           NULL,
    [RCA_InformationProvidedTrue]            INT           NULL,
    [RCA_ProposedContractSuitable]           INT           NULL,
    [RCA_TermsUnderstood]                    INT           NULL,
    [RCA_FinalAssessmentRequested]           INT           NULL,
    [RCA_MLTFDocsChecked]                    INT           NULL,
    [RCA_MLTFIncident]                       INT           NULL,
    [RCA_MLTFIncidentSeverity]               INT           NULL,
    [RCA_MLTFRiskScore]                      VARCHAR (40)  NULL,
    [RCA_ComparableTwoMonths]                INT           NULL,
    [RCA_IncomeReviewPeriod]                 INT           NULL,
    [RCA_StatementDays]                      INT           NULL,
    CONSTRAINT [PK_iO_Product_CheckListAssessment] PRIMARY KEY CLUSTERED ([RCA_ID] ASC) WITH (FILLFACTOR = 85)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Primary Key.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'iO_Product_CheckListAssessment', @level2type = N'COLUMN', @level2name = N'RCA_ID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Redundant.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'iO_Product_CheckListAssessment', @level2type = N'COLUMN', @level2name = N'RCA_Ownership';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Used to compare records in Replication process.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'iO_Product_CheckListAssessment', @level2type = N'COLUMN', @level2name = N'RCA_IDLink_Version';

