CREATE TABLE [dbo].[iO_Product_LoanAssetProperty] (
    [RLAp_ID]                    VARCHAR (40)  NOT NULL,
    [RLAp_Ownership]             VARCHAR (40)  NOT NULL,
    [RLAp_IDLink_Sync]           VARCHAR (40)  NULL,
    [RLAp_IDLink_RMR]            VARCHAR (40)  NOT NULL,
    [RLAp_IDLink_CMR]            VARCHAR (40)  NULL,
    [RLAP_IDLink_StreetType]     VARCHAR (40)  NULL,
    [RLAp_IDLink_Country]        VARCHAR (40)  NULL,
    [RLAp_EstimatedValue]        FLOAT (53)    NULL,
    [RLAp_PropertyName]          VARCHAR (255) NULL,
    [RLAp_UnitNumber]            VARCHAR (50)  NULL,
    [RLAp_StreetNumber]          VARCHAR (50)  NULL,
    [RLAp_StreetName]            VARCHAR (255) NULL,
    [RLAp_Direction]             VARCHAR (50)  NULL,
    [RLAp_City]                  VARCHAR (255) NULL,
    [RLAp_State]                 VARCHAR (255) NULL,
    [RLAp_PostCode]              VARCHAR (10)  NULL,
    [RLAp_IDLink_Version]        VARCHAR (40)  NULL,
    [RLAp_SeqNumber]             BIGINT        IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [RLAp_ProprietorName]        TEXT          NULL,
    [RLAp_PurchasedDate]         VARCHAR (50)  NULL,
    [RLAp_RegisteredProprietor]  VARCHAR (255) NULL,
    [RLAp_OccupancyFCXID]        VARCHAR (50)  NULL,
    [RLAp_IDLink_XRTy]           VARCHAR (40)  NULL,
    [RLAp_IDLink_XRTu]           VARCHAR (40)  NULL,
    [RLAp_IDLink_XRTt]           VARCHAR (40)  NULL,
    [RLAp_IDLink_XRTp]           VARCHAR (40)  NULL,
    [RLAp_IDLink_XRTgt]          VARCHAR (40)  NULL,
    [RLAp_IDLink_XRTgc]          VARCHAR (40)  NULL,
    [RLAp_IDLink_XRTht]          VARCHAR (40)  NULL,
    [RLAp_IDLink_XRTus]          VARCHAR (40)  NULL,
    [RLAp_IDLink_XRTul]          VARCHAR (40)  NULL,
    [RLAp_IDLink_XRTc]           VARCHAR (40)  NULL,
    [RLAp_IDLink_XRTvi]          VARCHAR (40)  NULL,
    [RLAp_IDLink_XRTro]          VARCHAR (40)  NULL,
    [RLAp_IDLink_XRTz]           VARCHAR (40)  NULL,
    [RLAp_IDLink_XRTs]           VARCHAR (40)  NULL,
    [RLAp_IDLink_XRTw]           VARCHAR (40)  NULL,
    [RLAp_IDLink_XRTl]           VARCHAR (40)  NULL,
    [RLAp_IDLink_XRPT]           VARCHAR (40)  NULL,
    [RLAp_Type]                  INT           NULL,
    [RLAp_IDUser]                INT           NULL,
    [RLAp_PurchasePrice]         FLOAT (53)    NULL,
    [RLAp_ActionType]            INT           NULL,
    [RLAp_AccessName]            TEXT          NULL,
    [RLAp_AccessNumberWork]      VARCHAR (50)  NULL,
    [RLAp_AccessNumberHome]      VARCHAR (50)  NULL,
    [RLAp_AccessNumberMobile]    VARCHAR (50)  NULL,
    [RLAp_AccessNote]            TEXT          NULL,
    [RLAp_NameOnDeed]            TEXT          NULL,
    [RLAp_BookNumber]            VARCHAR (50)  NULL,
    [RLAp_CertID]                VARCHAR (50)  NULL,
    [RLAp_CT]                    VARCHAR (50)  NULL,
    [RLAp_FolioNumber]           VARCHAR (50)  NULL,
    [RLAp_LotNo]                 VARCHAR (50)  NULL,
    [RLAp_LpDp]                  VARCHAR (50)  NULL,
    [RLAp_Number]                VARCHAR (50)  NULL,
    [RLAp_Parish]                VARCHAR (50)  NULL,
    [RLAp_County]                VARCHAR (50)  NULL,
    [RLAp_SubDiv]                VARCHAR (50)  NULL,
    [RLAp_VolNo]                 VARCHAR (50)  NULL,
    [RLAp_TenantName]            VARCHAR (255) NULL,
    [RLAp_GrossWeeklyRent]       FLOAT (53)    NULL,
    [RLAp_RegistrationNumber]    VARCHAR (50)  NULL,
    [RLAp_DateRegistered]        VARCHAR (255) NULL,
    [RLAp_StampedTo]             VARCHAR (512) NULL,
    [RLAp_AccessNumber]          TEXT          NULL,
    [RLAp_DateDischarged]        VARCHAR (255) NULL,
    [RLAp_PropertyZoning]        VARCHAR (MAX) NULL,
    [RLAp_CurrentMarketValue]    FLOAT (53)    NULL,
    [RLAp_AccessContactType]     TEXT          NULL,
    [RLAp_InactiveSecurity]      VARCHAR (MAX) NULL,
    [RLAp_LandSize]              VARCHAR (50)  NULL,
    [RLAp_StudioSize]            VARCHAR (50)  NULL,
    [RLAp_EstRentalValue]        FLOAT (53)    NULL,
    [RLAp_LandValue]             FLOAT (53)    NULL,
    [RLAp_ValuationPostcode]     VARCHAR (50)  NULL,
    [RLAp_BedroomCount]          INT           NULL,
    [RLAp_BathroomCount]         INT           NULL,
    [RLAp_KitchenCount]          INT           NULL,
    [RLAp_FloorCount]            INT           NULL,
    [RLAp_UnitCount]             INT           NULL,
    [RLAp_HeatingValue]          FLOAT (53)    NULL,
    [RLAp_HeatingType]           VARCHAR (MAX) NULL,
    [RLAp_IsServiceOrManaged]    VARCHAR (MAX) NULL,
    [RLAp_SuiteNumber]           VARCHAR (50)  NULL,
    [RLAp_FloorNumber]           VARCHAR (50)  NULL,
    [RLAp_HighRisk]              VARCHAR (MAX) NULL,
    [RLAp_HighRiskOverride]      VARCHAR (MAX) NULL,
    [RLAp_LocationTypeCode]      VARCHAR (50)  NULL,
    [RLAp_BuilderName]           VARCHAR (255) NULL,
    [RLAp_FeesIncludeHeatFlag]   VARCHAR (MAX) NULL,
    [RLAp_IncludesTDS]           VARCHAR (MAX) NULL,
    [RLAp_InsulatedWithUFFI]     VARCHAR (MAX) NULL,
    [RLAp_LegalLine1]            VARCHAR (MAX) NULL,
    [RLAp_LegalLine2]            VARCHAR (MAX) NULL,
    [RLAp_LegalLine3]            VARCHAR (MAX) NULL,
    [RLAp_MLSListing]            VARCHAR (MAX) NULL,
    [RLAp_Note]                  TEXT          NULL,
    [RLAp_IsPrimary]             VARCHAR (MAX) NULL,
    [RLAp_AppraisalRequested]    VARCHAR (50)  NULL,
    [RLAp_AgeOfStructure]        INT           NULL,
    [RLAp_SubjectProperty]       VARCHAR (MAX) NULL,
    [RLAp_YearBuilt]             INT           NULL,
    [RLAp_TaxationYear]          INT           NULL,
    [RLAp_OriginalPurchasePrice] FLOAT (53)    NULL,
    [RLAp_OriginalPurchaseDate]  VARCHAR (50)  NULL,
    [RLAp_AnnualIncomeAmt]       FLOAT (53)    NULL,
    [RLAp_IncomeDesc]            VARCHAR (MAX) NULL,
    [RLAp_IncomePctGDS]          FLOAT (53)    NULL,
    [RLAp_IncomePctTDS]          FLOAT (53)    NULL,
    [RLAp_IDLink_XFR]            VARCHAR (40)  NULL,
    [RLAp_IDLink_XIN]            VARCHAR (40)  NULL,
    [RLAp_IncomeAmt]             FLOAT (53)    NULL,
    CONSTRAINT [PK_iO_Product_LoanAssetProperty] PRIMARY KEY CLUSTERED ([RLAp_ID] ASC) WITH (FILLFACTOR = 85)
);


GO
CREATE NONCLUSTERED INDEX [IX_iO_Product_LoanAssetProperty_10]
    ON [dbo].[iO_Product_LoanAssetProperty]([RLAp_IDLink_RMR] ASC, [RLAp_ID] ASC) WITH (FILLFACTOR = 85);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Primary Key.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'iO_Product_LoanAssetProperty', @level2type = N'COLUMN', @level2name = N'RLAp_ID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Redundant.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'iO_Product_LoanAssetProperty', @level2type = N'COLUMN', @level2name = N'RLAp_Ownership';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Used to compare records in Replication process.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'iO_Product_LoanAssetProperty', @level2type = N'COLUMN', @level2name = N'RLAp_IDLink_Version';

