CREATE TABLE [dbo].[lc_balance07062013] (
    [Branch]                VARCHAR (512)  NULL,
    [BranchRefer]           VARCHAR (512)  NULL,
    [ClientNo]              BIGINT         NULL,
    [LoanNo]                BIGINT         NULL,
    [PrimaryClient]         NVARCHAR (MAX) NULL,
    [LodgeDate]             DATETIME       NULL,
    [SettleDate]            DATETIME       NULL,
    [Prod_Type]             VARCHAR (512)  NULL,
    [Prod_Status]           VARCHAR (512)  NULL,
    [ProdStat2]             VARCHAR (512)  NULL,
    [Broker]                VARCHAR (512)  NULL,
    [Broker Contact]        VARCHAR (512)  NULL,
    [Employer]              VARCHAR (255)  NULL,
    [position]              VARCHAR (255)  NULL,
    [AssessorName]          VARCHAR (512)  NULL,
    [Vendor]                VARCHAR (512)  NULL,
    [Security]              VARCHAR (255)  NULL,
    [Make]                  VARCHAR (512)  NULL,
    [Model]                 VARCHAR (512)  NULL,
    [Year]                  VARCHAR (10)   NULL,
    [Colour]                VARCHAR (512)  NULL,
    [Rego]                  VARCHAR (MAX)  NULL,
    [VinNum]                VARCHAR (MAX)  NULL,
    [EngNum]                VARCHAR (MAX)  NULL,
    [Reg State]             VARCHAR (10)   NULL,
    [GlassesValue]          FLOAT (53)     NULL,
    [PurchaseValue]         FLOAT (53)     NULL,
    [LoanPurpose]           VARCHAR (512)  NULL,
    [Term]                  INT            NULL,
    [Pay_Method]            VARCHAR (512)  NULL,
    [Deposit]               FLOAT (53)     NULL,
    [First Succ Pay Date]   DATETIME       NULL,
    [Loss Date]             DATETIME       NULL,
    [IntRate]               FLOAT (53)     NULL,
    [Applied For]           MONEY          NULL,
    [Cash Out]              MONEY          NULL,
    [Insurance]             MONEY          NULL,
    [Application Fee]       FLOAT (53)     NULL,
    [Brokerage]             MONEY          NULL,
    [TotalInterest]         MONEY          NULL,
    [Mthly Serv Fee]        MONEY          NULL,
    [Balance]               MONEY          NULL,
    [Received]              MONEY          NULL,
    [Dishonoured]           MONEY          NULL,
    [Net Received]          MONEY          NULL,
    [Frequency]             VARCHAR (255)  NULL,
    [Inst_Due]              FLOAT (53)     NULL,
    [Arrears]               FLOAT (53)     NULL,
    [NumDishon]             INT            NULL,
    [LodgeMonth]            DATETIME       NULL,
    [SettleMonth]           DATETIME       NULL,
    [Ageing]                VARCHAR (100)  NULL,
    [LVR]                   FLOAT (53)     NULL,
    [vehicle_age_inception] INT            NULL,
    [client_address]        VARCHAR (2284) NULL,
    [state]                 VARCHAR (512)  NULL,
    [post_code]             VARCHAR (10)   NULL,
    [BSBNO]                 VARCHAR (255)  NULL,
    [Account_number]        VARCHAR (255)  NULL,
    [fees_charged]          FLOAT (53)     NULL,
    [interest_charged]      FLOAT (53)     NULL,
    [opening_balance]       FLOAT (53)     NULL,
    [principal_balance]     FLOAT (53)     NULL,
    [bad_debt]              MONEY          NULL,
    [arrears_2]             FLOAT (53)     NULL,
    [ageingrange1_30]       MONEY          NULL,
    [ageingrange30_60]      MONEY          NULL,
    [ageingrange60_90]      MONEY          NULL,
    [ageingrange90plus]     MONEY          NULL
);

