CREATE TABLE [dbo].[tblExploreMtgApp] (
    [MtgAppID]                     DECIMAL (18)  NULL,
    [OriginatorID]                 VARCHAR (512) NULL,
    [MtgAppStatusNum]              DECIMAL (18)  NULL,
    [MtgAppStatusCode]             VARCHAR (50)  NULL,
    [UWUserID]                     VARCHAR (512) NULL,
    [IsPreapproval]                INT           NULL,
    [IsArchivedPreapproval]        INT           NULL,
    [OrigConditionsOutstanding]    INT           NULL,
    [TotConditionsOutstanding]     INT           NULL,
    [DaysUntilClose]               INT           NULL,
    [ApplicationID]                BIGINT        NULL,
    [ApplicationDate]              DATETIME      NULL,
    [TotalLoanAmount]              FLOAT (53)    NULL,
    [AmortizationTerm]             INT           NULL,
    [EstimatedClosingDate]         DATETIME      NULL,
    [DealTypeID]                   INT           NULL,
    [LenderProfileID]              VARCHAR (512) NULL,
    [SourceApplicationID]          VARCHAR (512) NULL,
    [DealPurposeID]                VARCHAR (50)  NULL,
    [SourceSystemMailBoxNbr]       VARCHAR (512) NULL,
    [LoanToValue]                  INT           NULL,
    [MITypeID]                     INT           NULL,
    [ReferenceDealNumber]          INT           NULL,
    [ReferenceDealTypeID]          INT           NULL,
    [TotalPurchasePrice]           FLOAT (53)    NULL,
    [PostedInterestRate]           INT           NULL,
    [UnderWriterUserID]            INT           NULL,
    [EstimatedPaymentAmount]       INT           NULL,
    [PandIPaymentAmount]           INT           NULL,
    [EscrowPaymentAmount]          INT           NULL,
    [MIPremiumAmount]              INT           NULL,
    [NetLoanAmount]                INT           NULL,
    [StatusDate]                   INT           NULL,
    [Discount]                     INT           NULL,
    [SecondaryFinancing]           INT           NULL,
    [DenialReasonID]               INT           NULL,
    [RenewalOptionsID]             INT           NULL,
    [NetInterestRate]              INT           NULL,
    [RateDate]                     INT           NULL,
    [BuyDownRate]                  INT           NULL,
    [SpecialFeatureID]             INT           NULL,
    [InterimInterestAmount]        INT           NULL,
    [DownPaymentAmount]            FLOAT (53)    NULL,
    [MortgageInsurerID]            INT           NULL,
    [MtgProdID]                    INT           NULL,
    [MIPolicyNumber]               INT           NULL,
    [FirstPaymentDate]             DATETIME      NULL,
    [NetPaymentAmount]             INT           NULL,
    [MILoanNumber]                 INT           NULL,
    [MaturityDate]                 DATETIME      NULL,
    [CommitmentIssueDate]          INT           NULL,
    [CommitmentAcceptDate]         INT           NULL,
    [RefExistingMtgNumber]         INT           NULL,
    [CombinedTotalLiabilities]     FLOAT (53)    NULL,
    [BankABANumber]                INT           NULL,
    [BankAccountNumber]            INT           NULL,
    [BankName]                     INT           NULL,
    [ActualClosingDate]            DATETIME      NULL,
    [CombinedTotalAssets]          FLOAT (53)    NULL,
    [CombinedTotalIncome]          FLOAT (53)    NULL,
    [CombinedTDS]                  FLOAT (53)    NULL,
    [CombinedGDS]                  FLOAT (53)    NULL,
    [RenewalDate]                  INT           NULL,
    [NumberOfBorrowers]            INT           NULL,
    [NumberOfGuarantors]           INT           NULL,
    [ServicingMortgageNumber]      INT           NULL,
    [PaymentTermID]                INT           NULL,
    [InterestTypeID]               INT           NULL,
    [PaymentFrequencyID]           INT           NULL,
    [PrepaymentOptionsID]          INT           NULL,
    [RateFormulaID]                INT           NULL,
    [StatusID]                     INT           NULL,
    [RiskRatingID]                 INT           NULL,
    [ElectronicSystemSource]       VARCHAR (512) NULL,
    [CommitmentExpirationDate]     INT           NULL,
    [RequestedSolicitorName]       INT           NULL,
    [RequestedAppraisorName]       INT           NULL,
    [BranchProfileID]              INT           NULL,
    [InterestAdjustmentDate]       INT           NULL,
    [PrivilegePaymentID]           INT           NULL,
    [AdvanceHold]                  INT           NULL,
    [ClientNumber]                 INT           NULL,
    [CombinedLTV]                  FLOAT (53)    NULL,
    [CombinedTotAnnualHeatingExp]  FLOAT (53)    NULL,
    [CombinedTotAnnualTaxExp]      FLOAT (53)    NULL,
    [CombinedTotCondoFeeExp]       FLOAT (53)    NULL,
    [CombinedTotPropertyExp]       FLOAT (53)    NULL,
    [CommitmentPeriod]             INT           NULL,
    [CommitmentProduced]           INT           NULL,
    [DatePreAppFirm]               INT           NULL,
    [FinanceProgramID]             INT           NULL,
    [MIPayorID]                    INT           NULL,
    [NewMoney]                     INT           NULL,
    [NextRateChangeDate]           INT           NULL,
    [NumberOfProperties]           INT           NULL,
    [OldMoney]                     INT           NULL,
    [OnHoldDate]                   INT           NULL,
    [PreApproval]                  INT           NULL,
    [Premium]                      INT           NULL,
    [RateLock]                     INT           NULL,
    [RateLockExpirationDate]       INT           NULL,
    [RateLockPeriod]               INT           NULL,
    [RefiCurrentBal]               INT           NULL,
    [RemainingBalanceSecondaryFin] INT           NULL,
    [ReturnDate]                   INT           NULL,
    [TaxPayorID]                   INT           NULL,
    [TotalActAppraisedValue]       FLOAT (53)    NULL,
    [TotalEstAppraisedValue]       FLOAT (53)    NULL,
    [TotalPropertyExpenses]        FLOAT (53)    NULL,
    [AdditionalPrincipal]          INT           NULL,
    [TotalPaymentAmount]           FLOAT (53)    NULL,
    [ActualPaymentTerm]            INT           NULL,
    [CombinedGDSBorrower]          INT           NULL,
    [CombinedTDSBorrower]          INT           NULL,
    [CombinedGDS3Year]             INT           NULL,
    [CombinedTDS3Year]             INT           NULL,
    [CombinedEquityAvailable]      INT           NULL,
    [EffectiveAmortizationMonths]  INT           NULL,
    [PostedRate]                   INT           NULL,
    [BlendedRate]                  INT           NULL,
    [ChannelMedia]                 INT           NULL,
    [ClosingTypeID]                INT           NULL,
    [MIUpfront]                    INT           NULL,
    [PreapprovalConclusionDate]    INT           NULL,
    [PreapprovalOriginalOfferDate] INT           NULL,
    [PreviouslyDeclined]           INT           NULL,
    [RequiredDownPayment]          INT           NULL,
    [MIIndicatorID]                INT           NULL,
    [RepaymentTypeID]              INT           NULL,
    [DecisionModificationTypeID]   INT           NULL,
    [ScenarioApproved]             INT           NULL,
    [ScenarioRecommended]          INT           NULL,
    [ScenarioNumber]               INT           NULL,
    [ScenarioDescription]          INT           NULL,
    [MIComments]                   INT           NULL,
    [MIStatusID]                   INT           NULL,
    [SystemTypeID]                 INT           NULL,
    [TotalFeeAmount]               FLOAT (53)    NULL,
    [MaximumLoanAmount]            INT           NULL,
    [ScenarioLocked]               INT           NULL,
    [TotalLoanBridgeAmount]        INT           NULL,
    [SolicitorSpecialInstructions] INT           NULL,
    [CombinedLendingValue]         INT           NULL,
    [ExistingLoanAmount]           INT           NULL,
    [GDSTDS3YearRate]              INT           NULL,
    [MaximumPrincipalAmount]       INT           NULL,
    [MaximumTDSExpensesAllowed]    INT           NULL,
    [MICommunicationFlag]          INT           NULL,
    [MIExistingPolicyNumber]       INT           NULL,
    [MinimumIncomeRequired]        INT           NULL,
    [PAPurchasePrice]              INT           NULL,
    [InstructionProduced]          INT           NULL,
    [TeaserDiscount]               INT           NULL,
    [TeaserMaturityDate]           INT           NULL,
    [TeaserNetInterestRate]        INT           NULL,
    [TeaserPIAmount]               INT           NULL,
    [TeaserTerm]                   INT           NULL,
    [CopyType]                     INT           NULL,
    [OpenMIResponseFlag]           INT           NULL,
    [ResolutionConditionID]        INT           NULL,
    [MIPremiumPST]                 INT           NULL,
    [PandIPaymentAmountMonthly]    INT           NULL,
    [FirstPaymentDateMonthly]      INT           NULL,
    [ProgressAdvance]              INT           NULL,
    [AdvanceToDateAmount]          INT           NULL,
    [AdvanceNumber]                INT           NULL,
    [MIRUIntervention]             INT           NULL,
    [RefiPurpose]                  INT           NULL,
    [RefiOrigPurchasePrice]        INT           NULL,
    [RefiBlendedAmortization]      INT           NULL,
    [RefiOrigMTGAmount]            INT           NULL,
    [RefiImprovementsDesc]         INT           NULL,
    [RefiImprovementAmount]        INT           NULL,
    [NextAdvanceAmount]            INT           NULL,
    [RefiOrigPurchaseDate]         INT           NULL,
    [RefiCurMortgageHolder]        INT           NULL,
    [ResubmissionFlag]             INT           NULL,
    [MIPolicyNumCMHC]              INT           NULL,
    [MIPolicyNumGE]                INT           NULL,
    [MCCMarketType]                INT           NULL,
    [IncomeVerificationTypeID]     INT           NULL,
    [RateCode]                     INT           NULL,
    [ProductDescription]           VARCHAR (35)  NULL,
    [BorrowerFirstName]            INT           NULL,
    [BorrowerMiddleInitial]        INT           NULL,
    [BorrowerLastName]             INT           NULL,
    [FirstTimeBuyer]               INT           NULL,
    [BorrowerBirthDate]            INT           NULL,
    [NSfocCurrencyTypeID]          INT           NULL,
    [SalutationID]                 INT           NULL,
    [MaritalStatusID]              INT           NULL,
    [SocialInsuranceNumber]        INT           NULL,
    [BorrowerHomePhoneNumber]      INT           NULL,
    [BorrowerWorkPhoneNumber]      INT           NULL,
    [BorrowerFaxNumber]            INT           NULL,
    [BorrowerEmailAddress]         INT           NULL,
    [ClientReferenceNumber]        INT           NULL,
    [NumberOfDependents]           INT           NULL,
    [NumberOfTimesBankrupt]        INT           NULL,
    [RaceID]                       INT           NULL,
    [CreditScore]                  INT           NULL,
    [GDS]                          INT           NULL,
    [TDS]                          INT           NULL,
    [EducationLevelID]             INT           NULL,
    [NetWorth]                     INT           NULL,
    [ExistingClient]               INT           NULL,
    [CreditSummary]                INT           NULL,
    [LanguagePreferenceID]         INT           NULL,
    [BorrowerGeneralStatusID]      INT           NULL,
    [BorrowerTypeID]               INT           NULL,
    [CitizenshipTypeID]            INT           NULL,
    [TotalAssetAmount]             INT           NULL,
    [TotalLiabilityAmount]         INT           NULL,
    [PaymentHistoryTypeID]         INT           NULL,
    [TotalIncomeAmount]            INT           NULL,
    [DateOfCreditBureauProfile]    INT           NULL,
    [CreditBureauOnFileDate]       INT           NULL,
    [BureauAttachment]             INT           NULL,
    [ExistingClientComments]       INT           NULL,
    [BankruptcyStatusID]           INT           NULL,
    [Age]                          INT           NULL,
    [StaffOfLender]                INT           NULL,
    [StaffType]                    INT           NULL,
    [TotalLiabilityPayments]       INT           NULL,
    [GDS3Year]                     INT           NULL,
    [TDS3Year]                     INT           NULL,
    [BorrowerWorkPhoneExtension]   INT           NULL,
    [BorrowerGenderID]             INT           NULL,
    [SmokeStatusID]                INT           NULL,
    [DisabilityStatusID]           INT           NULL,
    [LifeStatusID]                 INT           NULL,
    [GuarantorOtherLoans]          INT           NULL,
    [StreetTypeID]                 INT           NULL,
    [P_PropertyTypeID]             INT           NULL,
    [P_PropertyUsageID]            INT           NULL,
    [DwellingStyleID]              INT           NULL,
    [OccupancyTypeID]              INT           NULL,
    [PropertyStreetNumber]         INT           NULL,
    [PropertyStreetName]           INT           NULL,
    [PropertyAddressLine2]         INT           NULL,
    [PropertyCity]                 INT           NULL,
    [PropertyPostalFSA]            INT           NULL,
    [PropertyPostalLDU]            INT           NULL,
    [LegalLine1]                   INT           NULL,
    [LegalLine2]                   INT           NULL,
    [LegalLine3]                   INT           NULL,
    [YearBuilt]                    INT           NULL,
    [ProvinceID]                   INT           NULL,
    [PurchasePrice]                INT           NULL,
    [MunicipalityID]               INT           NULL,
    [UnitNumber]                   INT           NULL,
    [LotSize]                      INT           NULL,
    [NumberOfUnits]                INT           NULL,
    [PropertyLocationID]           INT           NULL,
    [StreetDirectionID]            INT           NULL,
    [LivingSpace]                  INT           NULL,
    [LivingSpaceUnitOfMeasureID]   INT           NULL,
    [DwellingTypeID]               INT           NULL,
    [LendingValue]                 INT           NULL,
    [MLSListingFlag]               INT           NULL,
    [SolicitorName]                INT           NULL,
    [SolicitorFirm]                INT           NULL,
    [SourceOfBusinessProfileID]    VARCHAR (512) NULL
);

