CREATE TABLE [dbo].[tblExploreMtgAppEODadition] (
    [MtgAppID]                      DECIMAL (18)  NULL,
    [OriginatorID]                  DECIMAL (18)  NULL,
    [MtgAppStatusNum]               DECIMAL (18)  NULL,
    [MtgAppStatusCode]              VARCHAR (8)   NULL,
    [UWUserID]                      DECIMAL (18)  NULL,
    [IsPreapproval]                 BIT           NULL,
    [IsArchivedPreapproval]         BIT           NULL,
    [OrigConditionsOutstanding]     INT           NULL,
    [TotConditionsOutstanding]      INT           NULL,
    [DaysUntilClose]                INT           NULL,
    [ApplicationID]                 VARCHAR (10)  NULL,
    [ApplicationDate]               DATETIME      NULL,
    [TotalLoanAmount]               DECIMAL (18)  NULL,
    [AmortizationTerm]              INT           NULL,
    [EstimatedClosingDate]          DATETIME      NULL,
    [DealTypeID]                    INT           NULL,
    [LenderProfileID]               DECIMAL (18)  NULL,
    [SourceApplicationID]           VARCHAR (35)  NULL,
    [DealPurposeID]                 INT           NULL,
    [SourceSystemMailBoxNbr]        VARCHAR (20)  NULL,
    [LoanToValue]                   DECIMAL (18)  NULL,
    [MITypeID]                      INT           NULL,
    [ReferenceDealNumber]           INT           NULL,
    [ReferenceDealTypeID]           INT           NULL,
    [TotalPurchasePrice]            DECIMAL (18)  NULL,
    [PostedInterestRate]            INT           NULL,
    [UnderWriterUserID]             INT           NULL,
    [EstimatedPaymentAmount]        INT           NULL,
    [PandIPaymentAmount]            DECIMAL (18)  NULL,
    [EscrowPaymentAmount]           INT           NULL,
    [MIPremiumAmount]               DECIMAL (18)  NULL,
    [NetLoanAmount]                 DECIMAL (18)  NULL,
    [StatusDate]                    DATETIME      NULL,
    [Discount]                      FLOAT (53)    NULL,
    [SecondaryFinancing]            INT           NULL,
    [DenialReasonID]                INT           NULL,
    [RenewalOptionsID]              INT           NULL,
    [NetInterestRate]               DECIMAL (18)  NULL,
    [RateDate]                      INT           NULL,
    [BuyDownRate]                   FLOAT (53)    NULL,
    [SpecialFeatureID]              INT           NULL,
    [InterimInterestAmount]         INT           NULL,
    [DownPaymentAmount]             DECIMAL (18)  NULL,
    [MortgageInsurerID]             INT           NULL,
    [MtgProdID]                     INT           NULL,
    [MIPolicyNumber]                VARCHAR (50)  NULL,
    [FirstPaymentDate]              DATETIME      NULL,
    [NetPaymentAmount]              INT           NULL,
    [MILoanNumber]                  INT           NULL,
    [MaturityDate]                  DATETIME      NULL,
    [CommitmentIssueDate]           DATETIME      NULL,
    [CommitmentAcceptDate]          INT           NULL,
    [RefExistingMtgNumber]          VARCHAR (50)  NULL,
    [CombinedTotalLiabilities]      DECIMAL (18)  NULL,
    [BankABANumber]                 VARCHAR (20)  NULL,
    [BankAccountNumber]             VARCHAR (20)  NULL,
    [BankName]                      VARCHAR (60)  NULL,
    [ActualClosingDate]             DATETIME      NULL,
    [CombinedTotalAssets]           DECIMAL (18)  NULL,
    [CombinedTotalIncome]           DECIMAL (18)  NULL,
    [CombinedTDS]                   DECIMAL (18)  NULL,
    [CombinedGDS]                   DECIMAL (18)  NULL,
    [RenewalDate]                   INT           NULL,
    [NumberOfBorrowers]             INT           NULL,
    [NumberOfGuarantors]            INT           NULL,
    [ServicingMortgageNumber]       VARCHAR (35)  NULL,
    [PaymentTermID]                 INT           NULL,
    [InterestTypeID]                INT           NULL,
    [PaymentFrequencyID]            INT           NULL,
    [PrepaymentOptionsID]           INT           NULL,
    [RateFormulaID]                 INT           NULL,
    [StatusID]                      INT           NULL,
    [RiskRatingID]                  INT           NULL,
    [ElectronicSystemSource]        INT           NULL,
    [CommitmentExpirationDate]      DATETIME      NULL,
    [RequestedSolicitorName]        INT           NULL,
    [RequestedAppraisorName]        INT           NULL,
    [BranchProfileID]               VARCHAR (1)   NULL,
    [InterestAdjustmentDate]        DATETIME      NULL,
    [PrivilegePaymentID]            INT           NULL,
    [AdvanceHold]                   INT           NULL,
    [ClientNumber]                  INT           NULL,
    [CombinedLTV]                   NUMERIC (18)  NULL,
    [CombinedTotAnnualHeatingExp]   DECIMAL (18)  NULL,
    [CombinedTotAnnualTaxExp]       DECIMAL (18)  NULL,
    [CombinedTotCondoFeeExp]        DECIMAL (18)  NULL,
    [CombinedTotPropertyExp]        DECIMAL (18)  NULL,
    [CommitmentPeriod]              INT           NULL,
    [CommitmentProduced]            VARCHAR (3)   NULL,
    [DatePreAppFirm]                INT           NULL,
    [FinanceProgramID]              INT           NULL,
    [MIPayorID]                     INT           NULL,
    [NewMoney]                      INT           NULL,
    [NextRateChangeDate]            INT           NULL,
    [NumberOfProperties]            INT           NULL,
    [OldMoney]                      INT           NULL,
    [OnHoldDate]                    INT           NULL,
    [PreApproval]                   CHAR (1)      NULL,
    [Premium]                       FLOAT (53)    NULL,
    [RateLock]                      INT           NULL,
    [RateLockExpirationDate]        INT           NULL,
    [RateLockPeriod]                INT           NULL,
    [RefiCurrentBal]                INT           NULL,
    [RemainingBalanceSecondaryFin]  INT           NULL,
    [ReturnDate]                    INT           NULL,
    [TaxPayorID]                    INT           NULL,
    [TotalActAppraisedValue]        DECIMAL (18)  NULL,
    [TotalEstAppraisedValue]        DECIMAL (18)  NULL,
    [TotalPropertyExpenses]         DECIMAL (18)  NULL,
    [AdditionalPrincipal]           INT           NULL,
    [TotalPaymentAmount]            DECIMAL (18)  NULL,
    [ActualPaymentTerm]             INT           NULL,
    [CombinedGDSBorrower]           INT           NULL,
    [CombinedTDSBorrower]           INT           NULL,
    [CombinedGDS3Year]              INT           NULL,
    [CombinedTDS3Year]              INT           NULL,
    [CombinedEquityAvailable]       INT           NULL,
    [EffectiveAmortizationMonths]   INT           NULL,
    [PostedRate]                    DECIMAL (18)  NULL,
    [BlendedRate]                   INT           NULL,
    [ChannelMedia]                  VARCHAR (1)   NULL,
    [ClosingTypeID]                 INT           NULL,
    [MIUpfront]                     CHAR (1)      NULL,
    [PreapprovalConclusionDate]     DATETIME      NULL,
    [PreapprovalOriginalOfferDate]  DATETIME      NULL,
    [PreviouslyDeclined]            CHAR (1)      NULL,
    [RequiredDownPayment]           DECIMAL (18)  NULL,
    [MIIndicatorID]                 INT           NULL,
    [RepaymentTypeID]               INT           NULL,
    [DecisionModificationTypeID]    INT           NULL,
    [ScenarioApproved]              INT           NULL,
    [ScenarioRecommended]           CHAR (1)      NULL,
    [ScenarioNumber]                INT           NULL,
    [ScenarioDescription]           INT           NULL,
    [MIComments]                    INT           NULL,
    [MIStatusID]                    INT           NULL,
    [SystemTypeID]                  INT           NULL,
    [TotalFeeAmount]                DECIMAL (18)  NULL,
    [MaximumLoanAmount]             INT           NULL,
    [ScenarioLocked]                CHAR (1)      NULL,
    [TotalLoanBridgeAmount]         INT           NULL,
    [SolicitorSpecialInstructions]  INT           NULL,
    [CombinedLendingValue]          DECIMAL (18)  NULL,
    [ExistingLoanAmount]            INT           NULL,
    [GDSTDS3YearRate]               DECIMAL (18)  NULL,
    [MaximumPrincipalAmount]        INT           NULL,
    [MaximumTDSExpensesAllowed]     INT           NULL,
    [MICommunicationFlag]           INT           NULL,
    [MIExistingPolicyNumber]        VARCHAR (35)  NULL,
    [MinimumIncomeRequired]         INT           NULL,
    [PAPurchasePrice]               DECIMAL (18)  NULL,
    [InstructionProduced]           INT           NULL,
    [TeaserDiscount]                INT           NULL,
    [TeaserMaturityDate]            INT           NULL,
    [TeaserNetInterestRate]         INT           NULL,
    [TeaserPIAmount]                INT           NULL,
    [TeaserTerm]                    INT           NULL,
    [CopyType]                      CHAR (1)      NULL,
    [OpenMIResponseFlag]            INT           NULL,
    [ResolutionConditionID]         INT           NULL,
    [MIPremiumPST]                  DECIMAL (18)  NULL,
    [PandIPaymentAmountMonthly]     DECIMAL (18)  NULL,
    [FirstPaymentDateMonthly]       DATETIME      NULL,
    [ProgressAdvance]               CHAR (1)      NULL,
    [AdvanceToDateAmount]           DECIMAL (18)  NULL,
    [AdvanceNumber]                 INT           NULL,
    [MIRUIntervention]              CHAR (1)      NULL,
    [RefiPurpose]                   INT           NULL,
    [RefiOrigPurchasePrice]         DECIMAL (18)  NULL,
    [RefiBlendedAmortization]       INT           NULL,
    [RefiOrigMTGAmount]             INT           NULL,
    [RefiImprovementsDesc]          INT           NULL,
    [RefiImprovementAmount]         INT           NULL,
    [NextAdvanceAmount]             DECIMAL (18)  NULL,
    [RefiOrigPurchaseDate]          INT           NULL,
    [RefiCurMortgageHolder]         INT           NULL,
    [ResubmissionFlag]              INT           NULL,
    [MIPolicyNumCMHC]               VARCHAR (50)  NULL,
    [MIPolicyNumGE]                 VARCHAR (50)  NULL,
    [MCCMarketType]                 INT           NULL,
    [IncomeVerificationTypeID]      INT           NULL,
    [RateCode]                      VARCHAR (3)   NULL,
    [ProductDescription]            VARCHAR (90)  NULL,
    [BorrowerFirstName]             VARCHAR (20)  NULL,
    [BorrowerMiddleInitial]         CHAR (1)      NULL,
    [BorrowerLastName]              VARCHAR (20)  NULL,
    [FirstTimeBuyer]                CHAR (1)      NULL,
    [BorrowerBirthDate]             DATETIME      NULL,
    [NSfocCurrencyTypeID]           INT           NULL,
    [SalutationID]                  INT           NULL,
    [MaritalStatusID]               INT           NULL,
    [SocialInsuranceNumber]         CHAR (10)     NULL,
    [BorrowerHomePhoneNumber]       VARCHAR (14)  NULL,
    [BorrowerWorkPhoneNumber]       VARCHAR (14)  NULL,
    [BorrowerFaxNumber]             VARCHAR (14)  NULL,
    [BorrowerEmailAddress]          VARCHAR (50)  NULL,
    [ClientReferenceNumber]         VARCHAR (20)  NULL,
    [NumberOfDependents]            INT           NULL,
    [NumberOfTimesBankrupt]         INT           NULL,
    [RaceID]                        INT           NULL,
    [CreditScore]                   INT           NULL,
    [GDS]                           INT           NULL,
    [TDS]                           INT           NULL,
    [EducationLevelID]              INT           NULL,
    [NetWorth]                      FLOAT (53)    NULL,
    [ExistingClient]                CHAR (1)      NULL,
    [CreditSummary]                 INT           NULL,
    [LanguagePreferenceID]          INT           NULL,
    [BorrowerGeneralStatusID]       INT           NULL,
    [BorrowerTypeID]                INT           NULL,
    [CitizenshipTypeID]             INT           NULL,
    [TotalAssetAmount]              DECIMAL (18)  NULL,
    [TotalLiabilityAmount]          DECIMAL (18)  NULL,
    [PaymentHistoryTypeID]          INT           NULL,
    [TotalIncomeAmount]             DECIMAL (18)  NULL,
    [DateOfCreditBureauProfile]     DATETIME      NULL,
    [CreditBureauOnFileDate]        DATETIME      NULL,
    [BureauAttachment]              CHAR (1)      NULL,
    [ExistingClientComments]        INT           NULL,
    [BankruptcyStatusID]            INT           NULL,
    [Age]                           INT           NULL,
    [StaffOfLender]                 INT           NULL,
    [StaffType]                     INT           NULL,
    [TotalLiabilityPayments]        DECIMAL (18)  NULL,
    [GDS3Year]                      INT           NULL,
    [TDS3Year]                      INT           NULL,
    [BorrowerWorkPhoneExtension]    VARCHAR (40)  NULL,
    [BorrowerGenderID]              INT           NULL,
    [SmokeStatusID]                 INT           NULL,
    [DisabilityStatusID]            INT           NULL,
    [LifeStatusID]                  INT           NULL,
    [GuarantorOtherLoans]           CHAR (1)      NULL,
    [StreetTypeID]                  INT           NULL,
    [P_PropertyTypeID]              INT           NULL,
    [P_PropertyUsageID]             INT           NULL,
    [DwellingStyleID]               INT           NULL,
    [OccupancyTypeID]               INT           NULL,
    [PropertyStreetNumber]          VARCHAR (10)  NULL,
    [PropertyStreetName]            VARCHAR (20)  NULL,
    [PropertyAddressLine2]          INT           NULL,
    [PropertyCity]                  VARCHAR (20)  NULL,
    [PropertyPostalFSA]             CHAR (3)      NULL,
    [PropertyPostalLDU]             CHAR (3)      NULL,
    [LegalLine1]                    VARCHAR (35)  NULL,
    [LegalLine2]                    VARCHAR (35)  NULL,
    [LegalLine3]                    VARCHAR (35)  NULL,
    [YearBuilt]                     INT           NULL,
    [ProvinceID]                    INT           NULL,
    [PurchasePrice]                 DECIMAL (18)  NULL,
    [MunicipalityID]                INT           NULL,
    [UnitNumber]                    VARCHAR (10)  NULL,
    [LotSize]                       INT           NULL,
    [NumberOfUnits]                 INT           NULL,
    [PropertyLocationID]            INT           NULL,
    [StreetDirectionID]             INT           NULL,
    [LivingSpace]                   INT           NULL,
    [LivingSpaceUnitOfMeasureID]    INT           NULL,
    [DwellingTypeID]                INT           NULL,
    [LendingValue]                  DECIMAL (18)  NULL,
    [MLSListingFlag]                CHAR (1)      NULL,
    [SolicitorName]                 VARCHAR (150) NULL,
    [SolicitorFirm]                 INT           NULL,
    [SourceOfBusinessProfileID]     DECIMAL (18)  NULL,
    [AdminUserID]                   INT           NULL,
    [DBDUserID]                     INT           NULL,
    [PropertyUsageID]               INT           NULL,
    [PropertyTypeID]                INT           NULL,
    [OriginalMortgageNumber]        INT           NULL,
    [LineOfBusinessID]              INT           NULL,
    [MarsNameSearch]                INT           NULL,
    [MarsPropertySearch]            INT           NULL,
    [CommisionAmount]               INT           NULL,
    [InterestCompoundID]            INT           NULL,
    [InvestorProfileID]             INT           NULL,
    [SecondApproverID]              INT           NULL,
    [JointApproverID]               INT           NULL,
    [SourceFirmProfileID]           INT           NULL,
    [GroupProfileID]                INT           NULL,
    [AdministratorID]               INT           NULL,
    [PricingProfileID]              INT           NULL,
    [RefinanceNewMoney]             INT           NULL,
    [CrossSellProfileID]            INT           NULL,
    [FifthApproverID]               INT           NULL,
    [FinalApproverID]               INT           NULL,
    [FourthApproverID]              INT           NULL,
    [InvestorApproved]              INT           NULL,
    [InvestorConfirmationNumber]    INT           NULL,
    [LienHolderSecondaryFinancing]  INT           NULL,
    [LienPositionID]                INT           NULL,
    [SecondaryFinancingLienHolder]  INT           NULL,
    [SourceRefAppNbr]               INT           NULL,
    [ThirdApproverID]               INT           NULL,
    [ApprovalTypeID]                INT           NULL,
    [CheckNotesFlag]                INT           NULL,
    [ClosingDatePlus90Days]         INT           NULL,
    [PerdiemInterestAmount]         INT           NULL,
    [IADNumberOfDays]               INT           NULL,
    [FunderProfileID]               INT           NULL,
    [PrequalificationMICertNum]     INT           NULL,
    [BrokerCommPaid]                INT           NULL,
    [HoldReasonID]                  INT           NULL,
    [PmntPlusLifeDisability]        INT           NULL,
    [LifePremium]                   INT           NULL,
    [DisabilityPremium]             INT           NULL,
    [CombinedPremium]               INT           NULL,
    [InterestRateIncrement]         INT           NULL,
    [InterestRateIncLifeDisability] INT           NULL,
    [EquivalentInterestRate]        INT           NULL,
    [CommisionCode]                 INT           NULL,
    [MultiProject]                  INT           NULL,
    [ProprietairePlus]              INT           NULL,
    [ProprietairePlusLoc]           INT           NULL,
    [SourceApplicationVersion]      INT           NULL,
    [AddCreditCostInsIncurred]      INT           NULL,
    [TotalCreditCost]               INT           NULL,
    [IntWithoutInsCreditCost]       INT           NULL,
    [UploadSerialNumber]            INT           NULL,
    [FundingUploadDone]             INT           NULL,
    [InsuranceProportionsID]        INT           NULL,
    [LifePercentCoverageReq]        INT           NULL,
    [DisPercentCoverageReq]         INT           NULL,
    [HeatTypeID]                    INT           NULL,
    [NumberOfBedrooms]              INT           NULL,
    [InsulatedWithUffi]             INT           NULL,
    [MonthlyCondoFees]              INT           NULL,
    [LandValue]                     INT           NULL,
    [PropertyValueSource]           INT           NULL,
    [AppraisalSourceID]             INT           NULL,
    [EquityAvailable]               INT           NULL,
    [NewConstructionID]             INT           NULL,
    [UrbanSuburban]                 INT           NULL,
    [EstimatedAppraisalValue]       INT           NULL,
    [ActualAppraisalValue]          INT           NULL,
    [PrimaryPropertyFlag]           INT           NULL,
    [AprraisalDateAct]              INT           NULL,
    [LotSizeDepth]                  INT           NULL,
    [LotSizeFrontage]               INT           NULL,
    [LotSizeUnitOfMeasureID]        INT           NULL,
    [PropertyOccurenceNumber]       INT           NULL,
    [PropertyReferenceNumber]       INT           NULL,
    [SewageTypeID]                  INT           NULL,
    [WaterTypeID]                   INT           NULL,
    [StructureAge]                  INT           NULL,
    [P_TotalPropertyExpenses]       INT           NULL,
    [TotalAnnualTaxAmount]          INT           NULL,
    [Zoning]                        INT           NULL,
    [GarageSizeID]                  INT           NULL,
    [GarageTypeID]                  INT           NULL,
    [BuilderName]                   INT           NULL
);

